"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Locale = "zh-CN" | "zh-TW" | "en";

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Locale, Record<string, string>> = {
  "zh-CN": {
    // 导航栏
    "nav.home": "首页",
    "nav.features": "功能",
    "nav.more": "更多",
    "nav.jobSearch": "岗位查询",
    "nav.resumeManager": "简历管理",
    "nav.aiMatch": "AI选岗",
    "nav.atsOptimize": "ATS简历优化",
    "nav.mockInterview": "AI模拟面试",
    "nav.applications": "网申管理",
    "nav.autoApplication": "自动网申",
    "nav.admin": "后台管理",
    "nav.login": "登录",
    "footer.tagline": "专为海外留学生打造的一站式求职平台",
    "footer.rights": "版权所有。",
    "nav.getStarted": "登录",
    "nav.logout": "退出",
    // 功能卡片
    "features.title": "核心功能",
    "features.subtitle": "为您的求职之路提供全方位支持",
    "feature1.title": "AI智能选岗",
    "feature1.desc": "基于简历智能匹配岗位，精准推荐最适合的机会。",
    "feature2.title": "ATS简历优化",
    "feature2.desc": "针对ATS系统优化简历格式，提高通过率。",
    "feature3.title": "自动网申填写",
    "feature3.desc": "Chrome扩展自动填充网申表单，节省大量重复填写时间。",
    "feature4.title": "海量岗位资源",
    "feature4.desc": "聚合全球知名企业岗位信息，覆盖科技、金融、咨询等多个行业。",
    "feature5.title": "求职进度追踪",
    "feature5.desc": "实时追踪网申状态，管理求职进度，不错过任何机会。",
    "feature6.title": "AI 模拟面试",
    "feature6.desc": "与 AI 进行模拟面试，获得即时反馈，提升面试表现。",
    // AI 模拟面试页面
    "mockInterview.title": "AI 模拟面试",
    "mockInterview.subtitle": "与 AI 面试官进行真实场景模拟面试，获得即时反馈与专业总结",
    "mockInterview.setupTitle": "面试设置",
    "mockInterview.openSettings": "打开面试设置",
    "mockInterview.interviewType": "面试类型",
    "mockInterview.typeTechnical": "技术面试",
    "mockInterview.typeBehavioral": "行为面试",
    "mockInterview.typeCase": "案例面试",
    "mockInterview.typeMixed": "综合面试",
    "mockInterview.typeTechnicalDesc": "考察专业知识与技术能力",
    "mockInterview.typeBehavioralDesc": "考察软技能与过往经历",
    "mockInterview.typeCaseDesc": "考察分析与解决问题能力",
    "mockInterview.typeMixedDesc": "综合考察多方面能力",
    "mockInterview.jd": "目标岗位 JD（可选）",
    "mockInterview.jdPlaceholder": "粘贴岗位描述，AI 将生成更有针对性的面试问题...",
    "mockInterview.resume": "选择简历（可选）",
    "mockInterview.resumePlaceholder": "选择简历让面试更贴近你的背景",
    "mockInterview.resumeHint": "AI 面试官将结合你的简历经历进行提问",
    "mockInterview.start": "进入面试间",
    "mockInterview.starting": "正在准备面试...",
    "mockInterview.interviewer": "AI 面试官",
    "mockInterview.you": "你",
    "mockInterview.answerPlaceholder": "输入你的回答...",
    "mockInterview.thinking": "面试官正在思考...",
    "mockInterview.endInterview": "结束面试",
    "mockInterview.ending": "生成总结中...",
    "mockInterview.summaryTitle": "面试总结报告",
    "mockInterview.restart": "再来一场",
    "mockInterview.emptyHint": "面试即将开始，请准备",
    "mockInterview.startFailed": "面试启动失败，请重试",
    "mockInterview.sendFailed": "发送失败，请重试",
    "mockInterview.noSpeech": "未检测到语音，请靠近麦克风大声一点再试",
    "mockInterview.writingEvaluation": "面试官正在撰写评价，请稍候…",
    "mockInterview.earlyReady": "下一轮面试官已提前准备好，立即进入",
    "mockInterview.reportWriting": "面试委员会正在撰写评议报告，请稍候…",
    "mockInterview.reportRecorded": "已记录 {n} 字评议",
    "mockInterview.verdictPass": "建议通过",
    "mockInterview.verdictFail": "不建议通过",
    "mockInterview.vote": "委员会票数",
    "mockInterview.overallGrade": "综合评级",
    "mockInterview.statDuration": "面试总时长",
    "mockInterview.statWords": "回答总字数",
    "mockInterview.statTurns": "问答回合",
    "mockInterview.statProbes": "被追问次数",
    "mockInterview.statAvgResponse": "平均反应速度",
    "mockInterview.statSeconds": "秒",
    "mockInterview.panel": "本场面试官团",
    "mockInterview.committeeTitle": "面试官委员会评语",
    "mockInterview.keyMoment": "关键时刻",
    "mockInterview.yourAnswer": "你的回答",
    "mockInterview.roundN": "第 {n} 轮",
    "mockInterview.radarTitle": "能力拆解",
    "mockInterview.highlightsTitle": "关键时刻回放",
    "mockInterview.fatalMistakes": "致命失误",
    "mockInterview.bestMoment": "最佳高光",
    "mockInterview.consequence": "后果",
    "mockInterview.effect": "效果",
    "mockInterview.coach": "AI 教练",
    "mockInterview.actionPlanTitle": "下一步行动清单",
    "mockInterview.immediate": "立即要做的事",
    "mockInterview.practice": "专项练习推荐",
    "mockInterview.reading": "推荐阅读",
    "mockInterview.transcriptTitle": "完整面试笔录",
    "mockInterview.exportReport": "导出报告",
    "mockInterview.trend": "历史成长趋势",
    "mockInterview.targetCompany": "目标公司",
    "mockInterview.targetCompanyPlaceholder": "如：字节跳动 / Goldman Sachs",
    "mockInterview.companyRequired": "请先填写目标公司（本场所有面试官都将来自该公司）",
    "mockInterview.selectCompany": "选择公司（可选）",
    "mockInterview.selectJob": "选择岗位（可选）",
    "mockInterview.companyPlaceholder": "选择目标公司",
    "mockInterview.jobPlaceholder": "选择目标岗位",
    "mockInterview.cameraOff": "摄像头已关闭",
    "mockInterview.listening": "正在聆听...",
    "mockInterview.tapToSpeak": "点击开启免提对话",
    "mockInterview.micAlwaysOn": "免提开启中，直接开口说话",
    "mockInterview.voiceDetected": "正在聆听，说完停顿自动提交",
    "mockInterview.eliminatedTitle": "面试提前结束",
    "mockInterview.eliminatedDesc": "面试官决定提前结束本场面试。正在为你生成评估报告…",
    "mockInterview.wrapUpTitle": "面试结束",
    "mockInterview.wrapUpDesc": "面试官已结束本场面试，正在为你生成评估报告…",
    "mockInterview.dnaLoading": "正在解析公司面试基因…",
    "mockInterview.dnaTitle": "面试基因",
    "mockInterview.dnaCurated": "精调",
    "mockInterview.dnaCached": "已学习",
    "mockInterview.dnaGenerated": "AI 生成",
    "mockInterview.feedbackTitle": "这场面试有多像真实面试？",
    "mockInterview.feedbackSubtitle": "1 分钟反馈，帮我们打磨这家公司的面试基因",
    "mockInterview.feedbackScoreLow": "完全不像",
    "mockInterview.feedbackScoreHigh": "非常真实",
    "mockInterview.feedbackLowPlaceholder": "哪些地方不像真实面试？比如提问方式、追问角度、节奏…（选填）",
    "mockInterview.feedbackSkip": "跳过",
    "mockInterview.feedbackSubmit": "提交反馈",
    "mockInterview.feedbackSubmitting": "提交中…",
    "mockInterview.recording": "正在录音，松开结束",
    "mockInterview.interviewMode": "面试模式",
    "mockInterview.modeSingle": "单人面试",
    "mockInterview.modeSingleDesc": "一位面试官全程面试",
    "mockInterview.modeGauntlet": "闯关模式",
    "mockInterview.modeGauntletDesc": "多轮不同风格面试官连续挑战",
    "mockInterview.rounds": "闯关轮数",
    "mockInterview.roundUnit": "轮",
    "mockInterview.roundProgress": "第 {current}/{total} 轮",
    "mockInterview.roundTransition": "下一轮面试即将开始",
    "mockInterview.newInterviewer": "新面试官",
    "mockInterview.recognizing": "识别中...",
    "mockInterview.speaking": "面试官说话中...",
    "mockInterview.micError": "无法访问麦克风，请检查权限",
    "mockInterview.micDenied": "麦克风权限已被浏览器拒绝",
    "mockInterview.micNoDevice": "未检测到麦克风设备，请检查设备连接",
    "mockInterview.micBusy": "麦克风正被其他应用占用，请关闭后重试",
    "mockInterview.micDeniedGuide": "请点击浏览器地址栏左侧的锁形图标，将麦克风权限设为「允许」后重试；如果你正在嵌入预览面板中，浏览器会禁止麦克风，请改用下方按钮在新标签页打开",
    "mockInterview.openInNewTab": "在新标签页打开（可获得麦克风权限）",
    "mockInterview.cameraError": "无法访问摄像头，请检查权限",
    "mockInterview.subtitleOn": "字幕",
    "mockInterview.endConfirm": "确定要结束面试吗？将生成本次面试总结报告。",
    "mockInterview.noAnswerSkip": "本次面试未检测到任何回答，已结束且不生成评估报告",
    "mockInterview.summaryFailed": "总结生成失败，请重试",
    "mockInterview.retrySummary": "重新生成评估",
    "mockInterview.qaCount": "已进行 {count} 轮问答",
    // FAQs
    "faqs.title": "常见问题",
    "faqs.subtitle": "快速解答关于Rising Path平台的常见问题",
    "faqs.contact": "找不到答案？联系我们的",
    "faqs.contactLink": "客服团队",
    "faq1.q": "Rising Path是什么？",
    "faq1.a": "Rising Path是一个专为海外留学生打造的一站式求职平台，提供岗位查询、AI选岗、简历优化、自动网申等功能，帮助您高效求职。",
    "faq2.q": "如何使用访问码？",
    "faq2.a": "访问码是进入平台的凭证。在首页点击任意功能卡片，输入有效的访问码即可进入对应功能页面。每个访问码对应独立的用户空间。",
    "faq3.q": "支持哪些地区和行业？",
    "faq3.a": "我们覆盖全球主要留学目的地国家，包括美国、英国、加拿大、澳大利亚等。行业涵盖科技、金融、咨询、医疗等多个领域。",
    "faq4.q": "简历数据安全吗？",
    "faq4.a": "我们采用企业级数据加密和隔离技术，每个访问码的数据完全独立存储，确保您的信息安全。",
    "faq5.q": "如何联系客服？",
    "faq5.a": "您可以通过平台内的客服系统或发送邮件至support@risingpath.com联系我们的客服团队，我们会在24小时内回复。",
    // 平台介绍
    "intro.greeting": "亲爱的同学：",
    "intro.p1": "当几乎所有机构都在把自己包装成精致的都市丽人，穿西装在高档写字楼里谈「赋能」「赛道」时，我们选择一头扎进泥土里。泥土里有被折叠的真实信息——那些机构不愿明说「这个岗位今年只招三人」的数据；那些被包装成「独家」其实公开可查的链接；那些用漂亮话掩盖的冰冷但有用的行业真相。泥土里也有被消费升级和求职焦虑抛弃的普通学生——他们不是不想花十几万块买安心，是花不起；不是不想被精心服务，是发现所谓精心服务最终只是为了把自己塞进更贵的链条。",
    "intro.p2": "对于一个清醒意识到求职重要性的同学来说，能花极低的成本解决最直接的问题，就是最大的进步。",
    "intro.p3": "我们管这叫「决策降级」——不是消费降级，是把选择权、评判权、止损权，一样一样还给你。以前做一个求职决策，先被销售教育两小时，再被合同困住半年，最后被维权消耗一个月。现在，你来决定值不值，你来决定要不要继续，你来决定什么时候转身就走。",
    "intro.p4": "我们只负责一件事：把真正有用的工具，做到足够便宜、足够直接、足够没废话。",
    // 访问码页面
    "accessCode.title": "欢迎使用 Rising Path",
    "accessCode.subtitle": "输入您的专属访问码，开启智能求职之旅。AI 智能选岗、简历优化、自动网申，助力海外留学生拿到理想 Offer。",
    "accessCode.button": "进入平台",
    "accessCode.placeholder": "请输入访问码",
    "accessCode.error.empty": "请输入访问码",
    "accessCode.error.invalid": "访问码无效或已过期",
    "accessCode.error.failed": "验证失败，请稍后重试",
    // 功能页面
    "page.jobs.title": "岗位查询",
    "page.jobs.subtitle": "浏览海量岗位，找到最适合的机会",
    "page.resume.title": "简历管理",
    "page.resume.subtitle": "上传和管理您的简历",
    "page.aiMatch.title": "AI 智能选岗",
    "page.aiMatch.subtitle": "基于简历智能匹配岗位，精准推荐最适合的机会",
    "page.optimize.title": "ATS 简历优化",
    "page.optimize.subtitle": "针对 ATS 系统优化简历格式，提高通过率",
    "page.applications.title": "网申管理",
    "page.applications.subtitle": "实时追踪网申状态，管理求职进度",
    "page.fieldMappings.title": "自动网申",
    "page.fieldMappings.subtitle": "学习记录网申字段，自动填写表单",
    "page.loading": "加载中...",
    "page.error": "加载失败，请稍后重试",
    "page.noData": "暂无数据",
    "page.submit": "提交",
    "page.cancel": "取消",
    "page.save": "保存",
    "page.delete": "删除",
    "page.edit": "编辑",
    "page.add": "添加",
    "page.search": "搜索",
    "page.filter": "筛选",
    "page.all": "全部",
    "page.back": "返回",
    "page.next": "下一步",
    "page.previous": "上一步",
    "page.confirm": "确认",
    "page.close": "关闭",
    // 岗位查询页面
    "jobs.filter": "筛选",
    "jobs.region": "地区",
    "jobs.direction": "方向",
    "jobs.audience": "受众",
    "jobs.clearAll": "清除全部",
    "jobs.noOptions": "暂无选项",
    "jobs.loading": "加载中...",
    "jobs.noJobs": "暂无符合条件的岗位，请调整筛选条件",
    "jobs.active": "可投递",
    "jobs.inactive": "不可投递",
    "jobs.sponsor": "Sponsor",
    "jobs.noSponsor": "无Sponsor",
    "jobs.add": "添加",
    "jobs.added": "已添加",
    "jobs.viewDetail": "查看详情",
    "jobs.originalLink": "原链接",
    "jobs.foundJobs": "共找到",
    "jobs.jobsUnit": "个岗位",
    "jobs.loginFirst": "请先登录",
    "jobs.addFailed": "添加失败",
    "jobs.addFailedRetry": "添加失败，请重试",
    "jobs.searchPlaceholder": "搜索岗位名称或公司...",
    // 简历管理页面
    "resume.title": "简历管理",
    "resume.subtitle": "上传、管理你的简历，支持智能解析",
    "resume.uploaded": "已上传",
    "resume.resumesUnit": "份简历",
    "resume.nextStep": "你可以基于简历进行下一步操作",
    "resume.aiMatch": "AI选岗",
    "resume.optimize": "优化简历",
    "resume.noResume": "还没有简历？上传后可以享受更多服务",
    "resume.feature.aiMatch": "AI智能选岗",
    "resume.feature.optimize": "优化简历ATS",
    "resume.feature.autoApply": "一键填写网申",
    "resume.upload.title": "上传简历",
    "resume.upload.description": "支持 PDF、Word (.docx)、TXT 格式，系统将自动解析提取关键信息",
    "resume.upload.button": "上传简历",
    "resume.upload.uploading": "上传中...",
    "resume.upload.hint": "支持 PDF、Word (.docx)、TXT 格式，系统将自动提取姓名、联系方式、教育经历、工作经验、技能等信息",
    "resume.upload.selected": "已选择",
    "resume.upload.parsing": "正在上传并解析...",
    "resume.upload.complete": "上传完成！",
    "resume.myResumes": "我的简历",
    "resume.refresh": "刷新列表",
    "resume.loading": "加载中...",
    "resume.noResumes": "暂无简历，上传你的第一份简历吧",
    "resume.parsing": "解析中...",
    "resume.segTitle": "你的求职画像",
    "resume.segConfirmed": "已确认",
    "resume.segEdit": "修正分层",
    "resume.segStage": "求职阶段",
    "resume.segRegion": "目标地区",
    "resume.segRegionMulti": "可多选",
    "resume.segSchool": "院校背景",
    "resume.segExp": "实习经历",
    "resume.segExpValue": "{n}段（大厂{big}段）· 共{m}个月",
    "resume.segResult": "你的分层",
    "resume.segReason": "判定依据",
    "resume.segTier": "院校层级",
    "resume.segMajor": "专业匹配",
    "resume.segConfirm": "确认分层",
    "resume.segUpdating": "更新中…",
    "resume.segStage_junior": "低年级（实习预备）",
    "resume.segStage_senior": "高年级（校招全职）",
    "resume.segStage_experienced": "社招（在职跳槽）",
    "resume.segStage_returning_intern": "实习转正",
    "resume.segRegion_us": "美国",
    "resume.segRegion_uk": "英国",
    "resume.segRegion_sg": "新加坡",
    "resume.segRegion_cn_t1": "国内一线",
    "resume.segRegion_cn_t2": "国内二三线",
    "resume.segMatch_aligned": "对口专业",
    "resume.segMatch_related": "跨专业",
    "resume.segMatch_unrelated": "泛专业",
    "resume.extractFields": "提取字段",
    "resume.extracting": "提取中",
    "resume.extracted": "已提取",
    "resume.translate": "翻译",
    "resume.translating": "翻译中",
    "resume.fieldMapping": "字段映射",
    "resume.viewDetail": "查看详情",
    "resume.delete": "删除",
    "resume.profilePending": "正在生成求职画像…",
    "resume.profilePendingHint": "画像生成约需30秒，页面将自动刷新",
    "resume.profileProjects": "项目经历",
    "resume.profileIntention": "求职意向",
    "resume.profileTitle": "求职画像",
    "resume.monthsUnit": "个月",
    "resume.parseResult": "简历解析结果",
    "resume.structuredFields": "结构化字段",
    "resume.aiExtracted": "AI 提取",
    "resume.name": "姓名",
    "resume.email": "邮箱",
    "resume.phone": "电话",
    "resume.location": "地址",
    "resume.education": "教育背景",
    "resume.experience": "工作经历",
    "resume.skills": "技能标签",
    "resume.basicInfo": "基本信息",
    "resume.configureMapping": "配置字段映射",
    "resume.loginFirst": "请先登录",
    "resume.uploadFailed": "上传失败",
    "resume.uploadFailedRetry": "上传失败，请重试",
    "resume.deleteConfirm": "确定要删除这份简历吗？此操作不可撤销。",
    "resume.deleteFailed": "删除失败",
    "resume.deleteFailedRetry": "删除失败，请重试",
    "resume.extractSuccess": "字段提取成功！",
    "resume.extractFailed": "提取失败",
    "resume.extractFailedRetry": "提取失败，请重试",
    // AI智能选岗页面
    "aiMatch.title": "AI智能选岗",
    "aiMatch.subtitle": "基于你的简历，AI将智能分析并推荐最匹配的岗位",
    "aiMatch.startMatch": "开始匹配",
    "aiMatch.startMatchDesc": "选择一份简历，AI将分析你的技能和经验，匹配最合适的岗位",
    "aiMatch.selectResume": "选择简历",
    "aiMatch.selectResumePlaceholder": "选择要匹配的简历",
    "aiMatch.region": "地区",
    "aiMatch.direction": "方向",
    "aiMatch.noOptions": "暂无选项",
    "aiMatch.clearAll": "清除全部",
    "aiMatch.matching": "匹配中...",
    "aiMatch.startAiMatch": "开始AI匹配",
    "aiMatch.selected": "已选择：",
    "aiMatch.analyzing": "正在分析简历并匹配岗位...",
    "aiMatch.matchResults": "匹配结果",
    "aiMatch.recommendations": "个推荐",
    "aiMatch.total": "共",
    "aiMatch.matchScore": "匹配分数",
    "aiMatch.scoreHigh": "高度匹配",
    "aiMatch.scoreMedium": "中等匹配",
    "aiMatch.scoreLow": "匹配度较低",
    "aiMatch.matchReason": "匹配原因",
    "aiMatch.suggestions": "优化建议",
    "aiMatch.optimizeResume": "优化简历",
    "aiMatch.viewJob": "查看岗位",
    "aiMatch.emptyTitle": "选择简历开始匹配",
    "aiMatch.emptyDesc": "AI将分析你的简历内容，结合岗位要求，为你推荐最匹配的工作机会",
    // ATS简历优化页面
    "optimize.title": "ATS简历优化",
    "optimize.subtitle": "针对ATS系统优化简历，提高简历通过率和曝光率",
    "optimize.history": "优化历史",
    "optimize.english": "英文",
    "optimize.chinese": "中文",
    "optimize.settings": "优化设置",
    "optimize.settingsDesc": "选择简历并设置目标岗位，AI将针对性优化简历内容",
    "optimize.selectResume": "选择简历",
    "optimize.selectResumePlaceholder": "选择要优化的简历",
    "optimize.targetCompany": "目标公司（可选）",
    "optimize.targetCompanyPlaceholder": "如：Google, Apple...",
    "optimize.searchJdTitle": "从网络获取该岗位的描述和要求",
    "optimize.targetPosition": "目标岗位",
    "optimize.targetPositionPlaceholder": "如：软件工程师...",
    "optimize.targetRegion": "目标地区",
    "optimize.regionUs": "美国",
    "optimize.regionUk": "英国",
    "optimize.regionSg": "新加坡",
    "optimize.regionHk": "香港",
    "optimize.regionAu": "澳大利亚",
    "optimize.regionCa": "加拿大",
    "optimize.regionEu": "欧洲",
    "optimize.regionCn": "中国内地",
    "optimize.regionJp": "日本",
    "optimize.optimizing": "优化中...",
    "optimize.startOptimize": "开始优化",
    "optimize.clearJd": "清除JD",
    "optimize.jdLabel": "岗位JD（可选）",
    "optimize.jdHint": "粘贴目标岗位的JD，AI将针对性优化",
    "optimize.jdPlaceholder": "粘贴岗位描述（Job Description）到这里...\n\n例如：\nWe are looking for a Software Engineer who is proficient in Python, JavaScript, and cloud technologies...\nRequirements:\n- 3+ years of experience in full-stack development\n- Strong understanding of REST APIs\n- Experience with AWS or Azure",
    "optimize.jdSet": "已设置岗位描述",
    "optimize.jdSetDesc": "AI将基于以下岗位要求进行优化",
    "optimize.suggestionsTitle": "来自AI智能选岗的优化建议",
    "optimize.optimizingProgress": "AI正在优化简历...",
    "optimize.feature1Title": "关键词优化",
    "optimize.feature1Desc": "自动分析岗位要求，添加关键技能词汇",
    "optimize.feature2Title": "ATS友好格式",
    "optimize.feature2Desc": "优化简历格式，确保ATS系统正确解析",
    "optimize.feature3Title": "内容增强",
    "optimize.feature3Desc": "使用专业术语增强简历描述",
    "optimize.tipsTitle": "ATS优化建议",
    "optimize.tip1": "使用标准格式：避免复杂的表格和图片",
    "optimize.tip2": "关键词匹配：研究目标岗位的JD，使用相同术语",
    "optimize.tip3": "量化成果：用具体数字展示成就",
    "optimize.tip4": "清晰结构：使用标准章节标题",
    "optimize.resultTitle": "简历优化完成",
    "optimize.resultDesc": "AI已根据目标岗位优化了您的简历内容",
    "optimize.preview": "预览",
    "optimize.edit": "编辑",
    "optimize.copy": "复制",
    "optimize.save": "保存",
    "optimize.saved": "已保存",
    "optimize.translating": "转换中...",
    "optimize.translate": "中英文转换",
    "optimize.toChinese": "转为中文",
    "optimize.toEnglish": "转为英文",
    "optimize.current": "当前",
    "optimize.generating": "生成中...",
    "optimize.download": "下载简历",
    "optimize.originalResume": "原简历",
    "optimize.optimizedResume": "优化后简历",
    "optimize.atsBadge": "ATS优化",
    "optimize.alertFillFirst": "请先填写目标公司和岗位",
    "optimize.alertJdFailed": "获取岗位描述失败",
    "optimize.alertJdRetry": "获取岗位描述失败，请稍后重试",
    "optimize.alertWordFailed": "生成Word文档失败，请重试",
    "optimize.unknownResume": "未知简历",
    "optimize.copyName": "姓名",
    "optimize.copySummary": "个人简介",
    "optimize.copySkills": "专业技能",
    "optimize.copyExperience": "工作经历",
    "optimize.copyEducation": "教育背景",
    "optimize.copyProjects": "项目经历",
    "optimize.copyCertifications": "证书认证",
    // 展示页面
    "showcase.title": "Interactive 3D",
    "showcase.description": "Bring your UI to life with beautiful 3D scenes. Create immersive experiences that capture attention and enhance your design.",
    "showcase.clickToEnter": "点击任意处进入",
  },
  "zh-TW": {
    // 導航欄
    "nav.home": "首頁",
    "nav.features": "功能",
    "nav.more": "更多",
    "nav.jobSearch": "崗位查詢",
    "nav.resumeManager": "簡歷管理",
    "nav.aiMatch": "AI選崗",
    "nav.atsOptimize": "ATS簡歷優化",
    "nav.mockInterview": "AI模擬面試",
    "nav.applications": "網申管理",
    "nav.autoApplication": "自動網申",
    "nav.admin": "後台管理",
    "nav.login": "登入",
    "footer.tagline": "專為海外留學生打造的一站式求職平台",
    "footer.rights": "版權所有。",
    "nav.getStarted": "登錄",
    "nav.logout": "退出",
    // 功能卡片
    "features.title": "核心功能",
    "features.subtitle": "為您的求職之路提供全方位支援",
    "feature1.title": "AI智能選崗",
    "feature1.desc": "基於簡歷智能匹配崗位，精準推薦最適合的機會。",
    "feature2.title": "ATS簡歷優化",
    "feature2.desc": "針對ATS系統優化簡歷格式，提高通過率。",
    "feature3.title": "自動網申填寫",
    "feature3.desc": "Chrome擴展自動填充網申表單，節省大量重複填寫時間。",
    "feature4.title": "海量崗位資源",
    "feature4.desc": "聚合全球知名企業崗位資訊，覆蓋科技、金融、諮詢等多個行業。",
    "feature5.title": "求職進度追蹤",
    "feature5.desc": "實時追蹤網申狀態，管理求職進度，不錯過任何機會。",
    "feature6.title": "AI 模擬面試",
    "feature6.desc": "與 AI 進行模擬面試，獲得即時反饋，提升面試表現。",
    // AI 模拟面试页面
    "mockInterview.title": "AI 模擬面試",
    "mockInterview.subtitle": "與 AI 面試官進行真實場景模擬面試，獲得即時反饋與專業總結",
    "mockInterview.setupTitle": "面試設置",
    "mockInterview.openSettings": "打開面試設置",
    "mockInterview.interviewType": "面試類型",
    "mockInterview.typeTechnical": "技術面試",
    "mockInterview.typeBehavioral": "行為面試",
    "mockInterview.typeCase": "案例面試",
    "mockInterview.typeMixed": "綜合面試",
    "mockInterview.typeTechnicalDesc": "考察專業知識與技術能力",
    "mockInterview.typeBehavioralDesc": "考察軟技能與過往經歷",
    "mockInterview.typeCaseDesc": "考察分析與解決問題能力",
    "mockInterview.typeMixedDesc": "綜合考察多方面能力",
    "mockInterview.jd": "目標崗位 JD（可選）",
    "mockInterview.jdPlaceholder": "粘貼崗位描述，AI 將生成更有針對性的面試問題...",
    "mockInterview.resume": "選擇簡歷（可選）",
    "mockInterview.resumePlaceholder": "選擇簡歷讓面試更貼近你的背景",
    "mockInterview.resumeHint": "AI 面試官將結合你的簡歷經歷進行提問",
    "mockInterview.start": "進入面試間",
    "mockInterview.starting": "正在準備面試...",
    "mockInterview.interviewer": "AI 面試官",
    "mockInterview.you": "你",
    "mockInterview.answerPlaceholder": "輸入你的回答...",
    "mockInterview.thinking": "面試官正在思考...",
    "mockInterview.endInterview": "結束面試",
    "mockInterview.ending": "生成總結中...",
    "mockInterview.summaryTitle": "面試總結報告",
    "mockInterview.restart": "再來一場",
    "mockInterview.emptyHint": "面試即將開始，請準備",
    "mockInterview.startFailed": "面試啟動失敗，請重試",
    "mockInterview.sendFailed": "發送失敗，請重試",
    "mockInterview.noSpeech": "未檢測到語音，請靠近麥克風大聲一點再試",
    "mockInterview.writingEvaluation": "面試官正在撰寫評價，請稍候…",
    "mockInterview.earlyReady": "下一輪面試官已提前準備好，立即進入",
    "mockInterview.reportWriting": "面試委員會正在撰寫評議報告，請稍候…",
    "mockInterview.reportRecorded": "已記錄 {n} 字評議",
    "mockInterview.verdictPass": "建議通過",
    "mockInterview.verdictFail": "不建議通過",
    "mockInterview.vote": "委員會票數",
    "mockInterview.overallGrade": "綜合評級",
    "mockInterview.statDuration": "面試總時長",
    "mockInterview.statWords": "回答總字數",
    "mockInterview.statTurns": "問答回合",
    "mockInterview.statProbes": "被追問次數",
    "mockInterview.statAvgResponse": "平均反應速度",
    "mockInterview.statSeconds": "秒",
    "mockInterview.panel": "本場面試官團",
    "mockInterview.committeeTitle": "面試官委員會評語",
    "mockInterview.keyMoment": "關鍵時刻",
    "mockInterview.yourAnswer": "你的回答",
    "mockInterview.roundN": "第 {n} 輪",
    "mockInterview.radarTitle": "能力拆解",
    "mockInterview.highlightsTitle": "關鍵時刻回放",
    "mockInterview.fatalMistakes": "致命失誤",
    "mockInterview.bestMoment": "最佳高光",
    "mockInterview.consequence": "後果",
    "mockInterview.effect": "效果",
    "mockInterview.coach": "AI 教練",
    "mockInterview.actionPlanTitle": "下一步行動清單",
    "mockInterview.immediate": "立即要做的事",
    "mockInterview.practice": "專項練習推薦",
    "mockInterview.reading": "推薦閱讀",
    "mockInterview.transcriptTitle": "完整面試筆錄",
    "mockInterview.exportReport": "導出報告",
    "mockInterview.trend": "歷史成長趨勢",
    "mockInterview.targetCompany": "目標公司",
    "mockInterview.targetCompanyPlaceholder": "如：字節跳動 / Goldman Sachs",
    "mockInterview.companyRequired": "請先填寫目標公司（本場所有面試官都將來自該公司）",
    "mockInterview.summaryFailed": "總結生成失敗，請重試",
    "mockInterview.retrySummary": "重新生成評估",
    "mockInterview.noAnswerSkip": "本次面試未檢測到任何回答，已結束且不生成評估報告",
    "mockInterview.qaCount": "已進行 {count} 輪問答",
    "mockInterview.selectCompany": "選擇公司（可選）",
    "mockInterview.selectJob": "選擇崗位（可選）",
    "mockInterview.companyPlaceholder": "選擇目標公司",
    "mockInterview.jobPlaceholder": "選擇目標崗位",
    "mockInterview.cameraOff": "攝像頭已關閉",
    "mockInterview.listening": "正在聆聽...",
    "mockInterview.tapToSpeak": "點擊開啟免提對話",
    "mockInterview.micAlwaysOn": "免提開啟中，直接開口說話",
    "mockInterview.voiceDetected": "正在聆聽，說完停頓自動提交",
    "mockInterview.eliminatedTitle": "面試提前結束",
    "mockInterview.eliminatedDesc": "面試官決定提前結束本場面試。正在為你產生評估報告…",
    "mockInterview.wrapUpTitle": "面試結束",
    "mockInterview.wrapUpDesc": "面試官已結束本場面試，正在為你產生評估報告…",
    "mockInterview.dnaLoading": "正在解析公司面試基因…",
    "mockInterview.dnaTitle": "面試基因",
    "mockInterview.dnaCurated": "精調",
    "mockInterview.dnaCached": "已學習",
    "mockInterview.dnaGenerated": "AI 生成",
    "mockInterview.feedbackTitle": "這場面試有多像真實面試？",
    "mockInterview.feedbackSubtitle": "1 分鐘反饋，幫我們打磨這家公司的面試基因",
    "mockInterview.feedbackScoreLow": "完全不像",
    "mockInterview.feedbackScoreHigh": "非常真實",
    "mockInterview.feedbackLowPlaceholder": "哪些地方不像真實面試？比如提問方式、追問角度、節奏…（選填）",
    "mockInterview.feedbackSkip": "跳過",
    "mockInterview.feedbackSubmit": "提交反饋",
    "mockInterview.feedbackSubmitting": "提交中…",
    "mockInterview.recording": "正在錄音，鬆開結束",
    "mockInterview.interviewMode": "面試模式",
    "mockInterview.modeSingle": "單人面試",
    "mockInterview.modeSingleDesc": "一位面試官全程面試",
    "mockInterview.modeGauntlet": "闖關模式",
    "mockInterview.modeGauntletDesc": "多輪不同風格面試官連續挑戰",
    "mockInterview.rounds": "闖關輪數",
    "mockInterview.roundUnit": "輪",
    "mockInterview.roundProgress": "第 {current}/{total} 輪",
    "mockInterview.roundTransition": "下一輪面試即將開始",
    "mockInterview.newInterviewer": "新面試官",
    "mockInterview.recognizing": "識別中...",
    "mockInterview.speaking": "面試官說話中...",
    "mockInterview.micError": "無法訪問麥克風，請檢查權限",
    "mockInterview.micDenied": "麥克風權限已被瀏覽器拒絕",
    "mockInterview.micNoDevice": "未檢測到麥克風設備，請檢查設備連接",
    "mockInterview.micBusy": "麥克風正被其他應用佔用，請關閉後重試",
    "mockInterview.micDeniedGuide": "請點擊瀏覽器地址欄左側的鎖形圖標，將麥克風權限設為「允許」後重試；如果你正在嵌入預覽面板中，瀏覽器會禁止麥克風，請改用下方按鈕在新分頁開啟",
    "mockInterview.openInNewTab": "在新分頁開啟（可獲得麥克風權限）",
    "mockInterview.cameraError": "無法訪問攝像頭，請檢查權限",
    "mockInterview.subtitleOn": "字幕",
    "mockInterview.endConfirm": "確定要結束面試嗎？將生成本次面試總結報告。",
    // FAQs
    "faqs.title": "常見問題",
    "faqs.subtitle": "快速解答關於Rising Path平台的常見問題",
    "faqs.contact": "找不到答案？聯繫我們的",
    "faqs.contactLink": "客服團隊",
    "faq1.q": "Rising Path是什麼？",
    "faq1.a": "Rising Path是一個專為海外留學生打造的一站式求職平台，提供崗位查詢、AI選崗、簡歷優化、自動網申等功能，幫助您高效求職。",
    "faq2.q": "如何使用訪問碼？",
    "faq2.a": "訪問碼是進入平台的憑證。在首頁點擊任意功能卡片，輸入有效的訪問碼即可進入對應功能頁面。每個訪問碼對應獨立的用戶空間。",
    "faq3.q": "支援哪些地區和行業？",
    "faq3.a": "我們覆蓋全球主要留學目的地國家，包括美國、英國、加拿大、澳洲等。行業涵蓋科技、金融、諮詢、醫療等多個領域。",
    "faq4.q": "簡歷數據安全嗎？",
    "faq4.a": "我們採用企業級數據加密和隔離技術，每個訪問碼的數據完全獨立存儲，確保您的資訊安全。",
    "faq5.q": "如何聯繫客服？",
    "faq5.a": "您可以通過平台內的客服系統或發送郵件至support@risingpath.com聯繫我們的客服團隊，我們會在24小時內回覆。",
    // 平台介紹
    "intro.greeting": "親愛的同學：",
    "intro.p1": "當幾乎所有機構都在把自己包裝成精緻的都市麗人，穿西裝在高檔寫字樓裡談「賦能」「賽道」時，我們選擇一頭扎進泥土裡。泥土裡有被摺疊的真實資訊——那些機構不願明說「這個崗位今年只招三人」的數據；那些被包裝成「獨家」其實公開可查的連結；那些用漂亮話掩蓋的冰冷但有用的行業真相。泥土裡也有被消費升級和求職焦慮拋棄的普通學生——他們不是不想花十幾萬塊買安心，是花不起；不是不想被精心服務，是發現所謂精心服務最終只是為了把自己塞進更貴的鏈條。",
    "intro.p2": "對於一個清醒意識到求職重要性的同學來說，能花極低的成本解決最直接的問題，就是最大的進步。",
    "intro.p3": "我們管這叫「決策降級」——不是消費降級，是把選擇權、評判權、止損權，一樣一樣還給你。以前做一個求職決策，先被銷售教育兩小時，再被合同困住半年，最後被維權消耗一個月。現在，你來決定值不值，你來決定要不要繼續，你來決定什麼時候轉身就走。",
    "intro.p4": "我們只負責一件事：把真正有用的工具，做到足夠便宜、足夠直接、足夠沒廢話。",
    // 訪問碼頁面
    "accessCode.title": "歡迎使用 Rising Path",
    "accessCode.subtitle": "輸入您的專屬訪問碼，開啟智能求職之旅。AI 智能選崗、簡歷優化、自動網申，助力海外留學生拿到理想 Offer。",
    "accessCode.button": "進入平台",
    "accessCode.placeholder": "請輸入訪問碼",
    "accessCode.error.empty": "請輸入訪問碼",
    "accessCode.error.invalid": "訪問碼無效或已過期",
    "accessCode.error.failed": "驗證失敗，請稍後重試",
    // 功能頁面
    "page.jobs.title": "崗位查詢",
    "page.jobs.subtitle": "瀏覽海量崗位，找到最適合的機會",
    "page.resume.title": "簡歷管理",
    "page.resume.subtitle": "上傳和管理您的簡歷",
    "page.aiMatch.title": "AI 智能選崗",
    "page.aiMatch.subtitle": "基於簡歷智能匹配崗位，精準推薦最適合的機會",
    "page.optimize.title": "ATS 簡歷優化",
    "page.optimize.subtitle": "針對 ATS 系統優化簡歷格式，提高通過率",
    "page.applications.title": "網申管理",
    "page.applications.subtitle": "實時追蹤網申狀態，管理求職進度",
    "page.fieldMappings.title": "自動網申",
    "page.fieldMappings.subtitle": "學習記錄網申字段，自動填寫表單",
    "page.loading": "加載中...",
    "page.error": "加載失敗，請稍後重試",
    "page.noData": "暫無數據",
    "page.submit": "提交",
    "page.cancel": "取消",
    "page.save": "保存",
    "page.delete": "刪除",
    "page.edit": "編輯",
    "page.add": "添加",
    "page.search": "搜索",
    "page.filter": "篩選",
    "page.all": "全部",
    "page.back": "返回",
    "page.next": "下一步",
    "page.previous": "上一步",
    "page.confirm": "確認",
    "page.close": "關閉",
    // 崗位查詢頁面
    "jobs.filter": "篩選",
    "jobs.region": "地區",
    "jobs.direction": "方向",
    "jobs.audience": "受眾",
    "jobs.clearAll": "清除全部",
    "jobs.noOptions": "暫無選項",
    "jobs.loading": "加載中...",
    "jobs.noJobs": "暫無符合條件的崗位，請調整篩選條件",
    "jobs.active": "可投遞",
    "jobs.inactive": "不可投遞",
    "jobs.sponsor": "Sponsor",
    "jobs.noSponsor": "無Sponsor",
    "jobs.add": "添加",
    "jobs.added": "已添加",
    "jobs.viewDetail": "查看詳情",
    "jobs.originalLink": "原鏈接",
    "jobs.foundJobs": "共找到",
    "jobs.jobsUnit": "個崗位",
    "jobs.loginFirst": "請先登錄",
    "jobs.addFailed": "添加失敗",
    "jobs.addFailedRetry": "添加失敗，請重試",
    "jobs.searchPlaceholder": "搜索崗位名稱或公司...",
    // 簡歷管理頁面
    "resume.title": "簡歷管理",
    "resume.subtitle": "上傳、管理你的簡歷，支持智能解析",
    "resume.uploaded": "已上傳",
    "resume.resumesUnit": "份簡歷",
    "resume.nextStep": "你可以基於簡歷進行下一步操作",
    "resume.aiMatch": "AI選崗",
    "resume.optimize": "優化簡歷",
    "resume.noResume": "還沒有簡歷？上傳後可以享受更多服務",
    "resume.feature.aiMatch": "AI智能選崗",
    "resume.feature.optimize": "優化簡歷ATS",
    "resume.feature.autoApply": "一鍵填寫網申",
    "resume.upload.title": "上傳簡歷",
    "resume.upload.description": "支持 PDF、Word (.docx)、TXT 格式，系統將自動解析提取關鍵信息",
    "resume.upload.button": "上傳簡歷",
    "resume.upload.uploading": "上傳中...",
    "resume.upload.hint": "支持 PDF、Word (.docx)、TXT 格式，系統將自動提取姓名、聯繫方式、教育經歷、工作經驗、技能等信息",
    "resume.upload.selected": "已選擇",
    "resume.upload.parsing": "正在上傳並解析...",
    "resume.upload.complete": "上傳完成！",
    "resume.myResumes": "我的簡歷",
    "resume.refresh": "刷新列表",
    "resume.loading": "加載中...",
    "resume.noResumes": "暫無簡歷，上傳你的第一份簡歷吧",
    "resume.parsing": "解析中...",
    "resume.segTitle": "你的求職畫像",
    "resume.segConfirmed": "已確認",
    "resume.segEdit": "修正分層",
    "resume.segStage": "求職階段",
    "resume.segRegion": "目標地區",
    "resume.segRegionMulti": "可多選",
    "resume.segSchool": "院校背景",
    "resume.segExp": "實習經歷",
    "resume.segExpValue": "{n}段（大廠{big}段）· 共{m}個月",
    "resume.segResult": "你的分層",
    "resume.segReason": "判定依據",
    "resume.segTier": "院校層級",
    "resume.segMajor": "專業匹配",
    "resume.segConfirm": "確認分層",
    "resume.segUpdating": "更新中…",
    "resume.segStage_junior": "低年級（實習預備）",
    "resume.segStage_senior": "高年級（校招全職）",
    "resume.segStage_experienced": "社招（在職跳槽）",
    "resume.segStage_returning_intern": "實習轉正",
    "resume.segRegion_us": "美國",
    "resume.segRegion_uk": "英國",
    "resume.segRegion_sg": "新加坡",
    "resume.segRegion_cn_t1": "國內一線",
    "resume.segRegion_cn_t2": "國內二三線",
    "resume.segMatch_aligned": "對口專業",
    "resume.segMatch_related": "跨專業",
    "resume.segMatch_unrelated": "泛專業",
    "resume.extractFields": "提取字段",
    "resume.extracting": "提取中",
    "resume.extracted": "已提取",
    "resume.translate": "翻譯",
    "resume.translating": "翻譯中",
    "resume.fieldMapping": "字段映射",
    "resume.viewDetail": "查看詳情",
    "resume.delete": "刪除",
    "resume.profilePending": "正在生成求職畫像…",
    "resume.profilePendingHint": "畫像生成約需30秒，頁面將自動刷新",
    "resume.profileProjects": "項目經歷",
    "resume.profileIntention": "求職意向",
    "resume.profileTitle": "求職畫像",
    "resume.monthsUnit": "個月",
    "resume.parseResult": "簡歷解析結果",
    "resume.structuredFields": "結構化字段",
    "resume.aiExtracted": "AI 提取",
    "resume.name": "姓名",
    "resume.email": "郵箱",
    "resume.phone": "電話",
    "resume.location": "地址",
    "resume.education": "教育背景",
    "resume.experience": "工作經歷",
    "resume.skills": "技能標籤",
    "resume.basicInfo": "基本信息",
    "resume.configureMapping": "配置字段映射",
    "resume.loginFirst": "請先登錄",
    "resume.uploadFailed": "上傳失敗",
    "resume.uploadFailedRetry": "上傳失敗，請重試",
    "resume.deleteConfirm": "確定要刪除這份簡歷嗎？此操作不可撤銷。",
    "resume.deleteFailed": "刪除失敗",
    "resume.deleteFailedRetry": "刪除失敗，請重試",
    "resume.extractSuccess": "字段提取成功！",
    "resume.extractFailed": "提取失敗",
    "resume.extractFailedRetry": "提取失敗，請重試",
    // AI智能選崗頁面
    "aiMatch.title": "AI智能選崗",
    "aiMatch.subtitle": "基於你的簡歷，AI將智能分析並推薦最匹配的崗位",
    "aiMatch.startMatch": "開始匹配",
    "aiMatch.startMatchDesc": "選擇一份簡歷，AI將分析你的技能和經驗，匹配最合適的崗位",
    "aiMatch.selectResume": "選擇簡歷",
    "aiMatch.selectResumePlaceholder": "選擇要匹配的簡歷",
    "aiMatch.region": "地區",
    "aiMatch.direction": "方向",
    "aiMatch.noOptions": "暫無選項",
    "aiMatch.clearAll": "清除全部",
    "aiMatch.matching": "匹配中...",
    "aiMatch.startAiMatch": "開始AI匹配",
    "aiMatch.selected": "已選擇：",
    "aiMatch.analyzing": "正在分析簡歷並匹配崗位...",
    "aiMatch.matchResults": "匹配結果",
    "aiMatch.recommendations": "個推薦",
    "aiMatch.total": "共",
    "aiMatch.matchScore": "匹配分數",
    "aiMatch.scoreHigh": "高度匹配",
    "aiMatch.scoreMedium": "中等匹配",
    "aiMatch.scoreLow": "匹配度較低",
    "aiMatch.matchReason": "匹配原因",
    "aiMatch.suggestions": "優化建議",
    "aiMatch.optimizeResume": "優化簡歷",
    "aiMatch.viewJob": "查看崗位",
    "aiMatch.emptyTitle": "選擇簡歷開始匹配",
    "aiMatch.emptyDesc": "AI將分析你的簡歷內容，結合崗位要求，為你推薦最匹配的工作機會",
    // ATS簡歷優化頁面
    "optimize.title": "ATS簡歷優化",
    "optimize.subtitle": "針對ATS系統優化簡歷，提高簡歷通過率和曝光率",
    "optimize.history": "優化歷史",
    "optimize.english": "英文",
    "optimize.chinese": "中文",
    "optimize.settings": "優化設置",
    "optimize.settingsDesc": "選擇簡歷並設置目標崗位，AI將針對性優化簡歷內容",
    "optimize.selectResume": "選擇簡歷",
    "optimize.selectResumePlaceholder": "選擇要優化的簡歷",
    "optimize.targetCompany": "目標公司（可選）",
    "optimize.targetCompanyPlaceholder": "如：Google, Apple...",
    "optimize.searchJdTitle": "從網絡獲取該崗位的描述和要求",
    "optimize.targetPosition": "目標崗位",
    "optimize.targetPositionPlaceholder": "如：軟件工程師...",
    "optimize.targetRegion": "目標地區",
    "optimize.regionUs": "美國",
    "optimize.regionUk": "英國",
    "optimize.regionSg": "新加坡",
    "optimize.regionHk": "香港",
    "optimize.regionAu": "澳大利亞",
    "optimize.regionCa": "加拿大",
    "optimize.regionEu": "歐洲",
    "optimize.regionCn": "中國內地",
    "optimize.regionJp": "日本",
    "optimize.optimizing": "優化中...",
    "optimize.startOptimize": "開始優化",
    "optimize.clearJd": "清除JD",
    "optimize.jdLabel": "崗位JD（可選）",
    "optimize.jdHint": "粘貼目標崗位的JD，AI將針對性優化",
    "optimize.jdPlaceholder": "粘貼崗位描述（Job Description）到這裡...\n\n例如：\nWe are looking for a Software Engineer who is proficient in Python, JavaScript, and cloud technologies...\nRequirements:\n- 3+ years of experience in full-stack development\n- Strong understanding of REST APIs\n- Experience with AWS or Azure",
    "optimize.jdSet": "已設置崗位描述",
    "optimize.jdSetDesc": "AI將基於以下崗位要求進行優化",
    "optimize.suggestionsTitle": "來自AI智能選崗的優化建議",
    "optimize.optimizingProgress": "AI正在優化簡歷...",
    "optimize.feature1Title": "關鍵詞優化",
    "optimize.feature1Desc": "自動分析崗位要求，添加關鍵技能詞彙",
    "optimize.feature2Title": "ATS友好格式",
    "optimize.feature2Desc": "優化簡歷格式，確保ATS系統正確解析",
    "optimize.feature3Title": "內容增強",
    "optimize.feature3Desc": "使用專業術語增強簡歷描述",
    "optimize.tipsTitle": "ATS優化建議",
    "optimize.tip1": "使用標準格式：避免複雜的表格和圖片",
    "optimize.tip2": "關鍵詞匹配：研究目標崗位的JD，使用相同術語",
    "optimize.tip3": "量化成果：用具體數字展示成就",
    "optimize.tip4": "清晰結構：使用標準章節標題",
    "optimize.resultTitle": "簡歷優化完成",
    "optimize.resultDesc": "AI已根據目標崗位優化了您的簡歷內容",
    "optimize.preview": "預覽",
    "optimize.edit": "編輯",
    "optimize.copy": "複製",
    "optimize.save": "保存",
    "optimize.saved": "已保存",
    "optimize.translating": "轉換中...",
    "optimize.translate": "中英文轉換",
    "optimize.toChinese": "轉為中文",
    "optimize.toEnglish": "轉為英文",
    "optimize.current": "當前",
    "optimize.generating": "生成中...",
    "optimize.download": "下載簡歷",
    "optimize.originalResume": "原簡歷",
    "optimize.optimizedResume": "優化後簡歷",
    "optimize.atsBadge": "ATS優化",
    "optimize.alertFillFirst": "請先填寫目標公司和崗位",
    "optimize.alertJdFailed": "獲取崗位描述失敗",
    "optimize.alertJdRetry": "獲取崗位描述失敗，請稍後重試",
    "optimize.alertWordFailed": "生成Word文檔失敗，請重試",
    "optimize.unknownResume": "未知簡歷",
    "optimize.copyName": "姓名",
    "optimize.copySummary": "個人簡介",
    "optimize.copySkills": "專業技能",
    "optimize.copyExperience": "工作經歷",
    "optimize.copyEducation": "教育背景",
    "optimize.copyProjects": "項目經歷",
    "optimize.copyCertifications": "證書認證",
    // 展示頁面
    "showcase.title": "Interactive 3D",
    "showcase.description": "Bring your UI to life with beautiful 3D scenes. Create immersive experiences that capture attention and enhance your design.",
    "showcase.clickToEnter": "點擊任意處進入",
  },
  "en": {
    // Navigation
    "nav.home": "Home",
    "nav.features": "Features",
    "nav.more": "More",
    "nav.jobSearch": "Job Search",
    "nav.resumeManager": "Resume Manager",
    "nav.aiMatch": "AI Match",
    "nav.atsOptimize": "ATS Optimize",
    "nav.mockInterview": "AI Mock Interview",
    "nav.applications": "Applications",
    "nav.autoApplication": "Auto Application",
    "nav.admin": "Admin",
    "nav.login": "Log in",
    "footer.tagline": "One-stop career platform for international students",
    "footer.rights": "All rights reserved.",
    "nav.getStarted": "Login",
    "nav.logout": "Log out",
    // Features
    "features.title": "Core Features",
    "features.subtitle": "Comprehensive support for your career journey",
    "feature1.title": "AI Job Match",
    "feature1.desc": "Intelligently match jobs based on your resume, recommending the best opportunities.",
    "feature2.title": "ATS Resume Optimize",
    "feature2.desc": "Optimize resume format for ATS systems to improve success rate.",
    "feature3.title": "Auto Application",
    "feature3.desc": "Chrome extension auto-fills application forms, saving time on repetitive tasks.",
    "feature4.title": "Massive Job Resources",
    "feature4.desc": "Aggregates job info from global companies across tech, finance, consulting and more.",
    "feature5.title": "Application Tracking",
    "feature5.desc": "Track application status in real-time, manage your job search progress.",
    "feature6.title": "AI Mock Interview",
    "feature6.desc": "Practice interviews with AI, get instant feedback to improve your performance.",
    // AI Mock Interview Page
    "mockInterview.title": "AI Mock Interview",
    "mockInterview.subtitle": "Practice real-scenario interviews with an AI interviewer, get instant feedback and a professional summary",
    "mockInterview.setupTitle": "Interview Setup",
    "mockInterview.openSettings": "Open Interview Setup",
    "mockInterview.interviewType": "Interview Type",
    "mockInterview.typeTechnical": "Technical",
    "mockInterview.typeBehavioral": "Behavioral",
    "mockInterview.typeCase": "Case Study",
    "mockInterview.typeMixed": "Mixed",
    "mockInterview.typeTechnicalDesc": "Assess professional knowledge and technical skills",
    "mockInterview.typeBehavioralDesc": "Assess soft skills and past experience",
    "mockInterview.typeCaseDesc": "Assess analytical and problem-solving skills",
    "mockInterview.typeMixedDesc": "Comprehensive assessment across dimensions",
    "mockInterview.jd": "Target Job Description (Optional)",
    "mockInterview.jdPlaceholder": "Paste the job description for more targeted interview questions...",
    "mockInterview.resume": "Select Resume (Optional)",
    "mockInterview.resumePlaceholder": "Select a resume to personalize the interview",
    "mockInterview.resumeHint": "The AI interviewer will ask questions based on your resume",
    "mockInterview.start": "Enter Interview Room",
    "mockInterview.starting": "Preparing interview...",
    "mockInterview.interviewer": "AI Interviewer",
    "mockInterview.you": "You",
    "mockInterview.answerPlaceholder": "Type your answer...",
    "mockInterview.thinking": "Interviewer is thinking...",
    "mockInterview.endInterview": "End Interview",
    "mockInterview.ending": "Generating summary...",
    "mockInterview.summaryTitle": "Interview Summary Report",
    "mockInterview.restart": "Start New Interview",
    "mockInterview.emptyHint": "The interview is about to begin, get ready",
    "mockInterview.startFailed": "Failed to start interview, please try again",
    "mockInterview.sendFailed": "Failed to send, please try again",
    "mockInterview.noSpeech": "No speech detected. Please speak louder and try again",
    "mockInterview.writingEvaluation": "The interviewer is writing feedback, please wait…",
    "mockInterview.earlyReady": "Next interviewer is ready early — enter now",
    "mockInterview.reportWriting": "The hiring committee is writing the evaluation…",
    "mockInterview.reportRecorded": "{n} chars recorded",
    "mockInterview.verdictPass": "Recommended: PASS",
    "mockInterview.verdictFail": "Not Recommended",
    "mockInterview.vote": "Committee vote",
    "mockInterview.overallGrade": "Overall grade",
    "mockInterview.statDuration": "Duration",
    "mockInterview.statWords": "Words answered",
    "mockInterview.statTurns": "Q&A turns",
    "mockInterview.statProbes": "Probing questions",
    "mockInterview.statAvgResponse": "Avg. response",
    "mockInterview.statSeconds": "s",
    "mockInterview.panel": "The panel",
    "mockInterview.committeeTitle": "Committee Evaluations",
    "mockInterview.keyMoment": "Key moment",
    "mockInterview.yourAnswer": "Your answer",
    "mockInterview.roundN": "Round {n}",
    "mockInterview.radarTitle": "Competency Breakdown",
    "mockInterview.highlightsTitle": "Key Moments Replay",
    "mockInterview.fatalMistakes": "Fatal mistake",
    "mockInterview.bestMoment": "Best moment",
    "mockInterview.consequence": "Consequence",
    "mockInterview.effect": "Effect",
    "mockInterview.coach": "AI Coach",
    "mockInterview.actionPlanTitle": "Action Plan",
    "mockInterview.immediate": "Do immediately",
    "mockInterview.practice": "Targeted drills",
    "mockInterview.reading": "Recommended reading",
    "mockInterview.transcriptTitle": "Full Transcript",
    "mockInterview.exportReport": "Export report",
    "mockInterview.trend": "Progress trend",
    "mockInterview.targetCompany": "Target company",
    "mockInterview.targetCompanyPlaceholder": "e.g. ByteDance / Goldman Sachs",
    "mockInterview.companyRequired": "Please enter a target company first (all interviewers will be from this company)",
    "mockInterview.summaryFailed": "Failed to generate summary, please try again",
    "mockInterview.retrySummary": "Retry Evaluation",
    "mockInterview.noAnswerSkip": "No answers detected. Interview ended without generating an evaluation report.",
    "mockInterview.qaCount": "{count} Q&A rounds completed",
    "mockInterview.selectCompany": "Select Company (Optional)",
    "mockInterview.selectJob": "Select Position (Optional)",
    "mockInterview.companyPlaceholder": "Select target company",
    "mockInterview.jobPlaceholder": "Select target position",
    "mockInterview.cameraOff": "Camera off",
    "mockInterview.listening": "Listening...",
    "mockInterview.tapToSpeak": "Tap to start hands-free talk",
    "mockInterview.micAlwaysOn": "Hands-free on, just speak",
    "mockInterview.voiceDetected": "Listening… auto-submits when you pause",
    "mockInterview.eliminatedTitle": "Interview ended early",
    "mockInterview.eliminatedDesc": "The interviewer has ended this interview early. Generating your evaluation report…",
    "mockInterview.wrapUpTitle": "Interview complete",
    "mockInterview.wrapUpDesc": "The interviewer has wrapped up this session. Generating your evaluation report…",
    "mockInterview.dnaLoading": "Analyzing company interview DNA…",
    "mockInterview.dnaTitle": "Interview DNA",
    "mockInterview.dnaCurated": "Curated",
    "mockInterview.dnaCached": "Learned",
    "mockInterview.dnaGenerated": "AI generated",
    "mockInterview.feedbackTitle": "How realistic was this interview?",
    "mockInterview.feedbackSubtitle": "1-minute feedback to sharpen this company's interview DNA",
    "mockInterview.feedbackScoreLow": "Not at all",
    "mockInterview.feedbackScoreHigh": "Very realistic",
    "mockInterview.feedbackLowPlaceholder": "What felt off? Question style, follow-up angles, pacing… (optional)",
    "mockInterview.feedbackSkip": "Skip",
    "mockInterview.feedbackSubmit": "Submit feedback",
    "mockInterview.feedbackSubmitting": "Submitting…",
    "mockInterview.recording": "Recording, release to finish",
    "mockInterview.interviewMode": "Interview Mode",
    "mockInterview.modeSingle": "Single Interviewer",
    "mockInterview.modeSingleDesc": "One interviewer throughout",
    "mockInterview.modeGauntlet": "Gauntlet Mode",
    "mockInterview.modeGauntletDesc": "Consecutive rounds with different interviewer styles",
    "mockInterview.rounds": "Rounds",
    "mockInterview.roundUnit": "rounds",
    "mockInterview.roundProgress": "Round {current}/{total}",
    "mockInterview.roundTransition": "Next round starting",
    "mockInterview.newInterviewer": "New Interviewer",
    "mockInterview.recognizing": "Recognizing...",
    "mockInterview.speaking": "Interviewer speaking...",
    "mockInterview.micError": "Cannot access microphone, please check permissions",
    "mockInterview.micDenied": "Microphone permission was denied by the browser",
    "mockInterview.micNoDevice": "No microphone detected. Please check your device connection",
    "mockInterview.micBusy": "Microphone is in use by another app. Please close it and retry",
    "mockInterview.micDeniedGuide": "Click the lock icon on the left of the browser address bar and set microphone to \"Allow\", then retry. If you are inside an embedded preview panel, the browser blocks microphones — use the button below to open in a new tab",
    "mockInterview.openInNewTab": "Open in a new tab (enables microphone)",
    "mockInterview.cameraError": "Cannot access camera, please check permissions",
    "mockInterview.subtitleOn": "Subtitles",
    "mockInterview.endConfirm": "End the interview? A summary report will be generated.",
    // FAQs
    "faqs.title": "Frequently Asked Questions",
    "faqs.subtitle": "Quick answers to common questions about Rising Path platform",
    "faqs.contact": "Can't find the answer? Contact our",
    "faqs.contactLink": "customer support team",
    "faq1.q": "What is Rising Path?",
    "faq1.a": "Rising Path is an all-in-one career platform designed for international students, offering job search, AI matching, resume optimization, and auto-application features.",
    "faq2.q": "How to use access code?",
    "faq2.a": "Access code is your credential to enter the platform. Click any feature card on the homepage and enter a valid access code to access the corresponding feature page.",
    "faq3.q": "Which regions and industries are supported?",
    "faq3.a": "We cover major study abroad destinations including USA, UK, Canada, Australia. Industries include tech, finance, consulting, healthcare and more.",
    "faq4.q": "Is resume data secure?",
    "faq4.a": "We use enterprise-grade encryption and data isolation. Each access code's data is stored independently to ensure your information security.",
    "faq5.q": "How to contact support?",
    "faq5.a": "You can reach our support team through the in-platform support system or email support@risingpath.com. We'll respond within 24 hours.",
    // Platform Introduction
    "intro.greeting": "Dear Student,",
    "intro.p1": "While almost all agencies package themselves as polished urban professionals, wearing suits in fancy office buildings talking about \"empowerment\" and \"market segments,\" we choose to dive straight into the mud. In the mud lies the folded truth — data that agencies won't openly share like \"this position only hires three people this year\"; links that are packaged as \"exclusive\" but are actually publicly available; cold but useful industry truths hidden behind fancy words. The mud also holds ordinary students abandoned by consumption upgrades and job-seeking anxiety — they don't refuse to spend hundreds of thousands for peace of mind, they simply can't afford it; they don't refuse to be carefully served, they just realize that so-called careful service is ultimately just about squeezing them into a more expensive chain.",
    "intro.p2": "For a student who is clearly aware of the importance of job seeking, being able to solve the most direct problems at the lowest cost is the greatest progress.",
    "intro.p3": "We call this \"decision downgrade\" — not consumption downgrade, but returning the right to choose, judge, and cut losses back to you, one by one. Before, making a job-seeking decision meant being educated by sales for two hours, trapped by a contract for six months, and consumed by rights protection for a month. Now, you decide if it's worth it, you decide whether to continue, you decide when to walk away.",
    "intro.p4": "We are only responsible for one thing: making truly useful tools cheap enough, direct enough, and without nonsense.",
    // Access Code Page
    "accessCode.title": "Welcome to Rising Path",
    "accessCode.subtitle": "Enter your exclusive access code to start your intelligent job-seeking journey. AI job matching, resume optimization, and auto-application help international students land their ideal offers.",
    "accessCode.button": "Enter Platform",
    "accessCode.placeholder": "Enter access code",
    "accessCode.error.empty": "Please enter access code",
    "accessCode.error.invalid": "Invalid or expired access code",
    "accessCode.error.failed": "Verification failed, please try again later",
    // Feature Pages
    "page.jobs.title": "Job Search",
    "page.jobs.subtitle": "Browse massive job listings and find the best opportunities",
    "page.resume.title": "Resume Manager",
    "page.resume.subtitle": "Upload and manage your resumes",
    "page.aiMatch.title": "AI Job Match",
    "page.aiMatch.subtitle": "Intelligently match jobs based on your resume, recommending the best opportunities",
    "page.optimize.title": "ATS Resume Optimize",
    "page.optimize.subtitle": "Optimize resume format for ATS systems to improve success rate",
    "page.applications.title": "Applications",
    "page.applications.subtitle": "Track application status in real-time, manage your job search progress",
    "page.fieldMappings.title": "Auto Application",
    "page.fieldMappings.subtitle": "Learn and record application fields, auto-fill forms",
    "page.loading": "Loading...",
    "page.error": "Failed to load, please try again later",
    "page.noData": "No data",
    "page.submit": "Submit",
    "page.cancel": "Cancel",
    "page.save": "Save",
    "page.delete": "Delete",
    "page.edit": "Edit",
    "page.add": "Add",
    "page.search": "Search",
    "page.filter": "Filter",
    "page.all": "All",
    "page.back": "Back",
    "page.next": "Next",
    "page.previous": "Previous",
    "page.confirm": "Confirm",
    "page.close": "Close",
    // Jobs Page
    "jobs.filter": "Filter",
    "jobs.region": "Region",
    "jobs.direction": "Direction",
    "jobs.audience": "Audience",
    "jobs.clearAll": "Clear All",
    "jobs.noOptions": "No options",
    "jobs.loading": "Loading...",
    "jobs.noJobs": "No jobs found. Please adjust your filters.",
    "jobs.active": "Active",
    "jobs.inactive": "Inactive",
    "jobs.sponsor": "Sponsor",
    "jobs.noSponsor": "No Sponsor",
    "jobs.add": "Add",
    "jobs.added": "Added",
    "jobs.viewDetail": "View Details",
    "jobs.originalLink": "Original Link",
    "jobs.foundJobs": "Found",
    "jobs.jobsUnit": "jobs",
    "jobs.loginFirst": "Please login first",
    "jobs.addFailed": "Failed to add",
    "jobs.addFailedRetry": "Failed to add, please try again",
    "jobs.searchPlaceholder": "Search job title or company...",
    // Resume Page
    "resume.title": "Resume Manager",
    "resume.subtitle": "Upload and manage your resumes with AI parsing",
    "resume.uploaded": "Uploaded",
    "resume.resumesUnit": "resumes",
    "resume.nextStep": "You can proceed with the next steps based on your resume",
    "resume.aiMatch": "AI Match",
    "resume.optimize": "Optimize",
    "resume.noResume": "No resume yet? Upload to unlock more features",
    "resume.feature.aiMatch": "AI Job Match",
    "resume.feature.optimize": "ATS Optimize",
    "resume.feature.autoApply": "Auto Apply",
    "resume.upload.title": "Upload Resume",
    "resume.upload.description": "Supports PDF, Word (.docx), TXT formats. System will automatically parse key information",
    "resume.upload.button": "Upload Resume",
    "resume.upload.uploading": "Uploading...",
    "resume.upload.hint": "Supports PDF, Word (.docx), TXT formats. System will extract name, contact, education, experience, skills, etc.",
    "resume.upload.selected": "Selected",
    "resume.upload.parsing": "Uploading and parsing...",
    "resume.upload.complete": "Upload complete!",
    "resume.myResumes": "My Resumes",
    "resume.refresh": "Refresh",
    "resume.loading": "Loading...",
    "resume.noResumes": "No resumes yet. Upload your first resume!",
    "resume.parsing": "Parsing...",
    "resume.segTitle": "Your Candidate Profile",
    "resume.segConfirmed": "Confirmed",
    "resume.segEdit": "Adjust",
    "resume.segStage": "Career Stage",
    "resume.segRegion": "Target Region",
    "resume.segRegionMulti": "multi-select",
    "resume.segSchool": "Education",
    "resume.segExp": "Internships",
    "resume.segExpValue": "{n} roles ({big} big-name) · {m} months",
    "resume.segResult": "Your Segment",
    "resume.segReason": "Rationale",
    "resume.segTier": "School Tier",
    "resume.segMajor": "Major Fit",
    "resume.segConfirm": "Confirm",
    "resume.segUpdating": "Saving…",
    "resume.segStage_junior": "Junior (pre-internship)",
    "resume.segStage_senior": "Senior (new grad)",
    "resume.segStage_experienced": "Experienced hire",
    "resume.segStage_returning_intern": "Return-offer track",
    "resume.segRegion_us": "United States",
    "resume.segRegion_uk": "United Kingdom",
    "resume.segRegion_sg": "Singapore",
    "resume.segRegion_cn_t1": "China Tier-1",
    "resume.segRegion_cn_t2": "China Tier-2/3",
    "resume.segMatch_aligned": "Aligned major",
    "resume.segMatch_related": "Related major",
    "resume.segMatch_unrelated": "Unrelated major",
    "resume.extractFields": "Extract Fields",
    "resume.extracting": "Extracting",
    "resume.extracted": "Extracted",
    "resume.translate": "Translate",
    "resume.translating": "Translating",
    "resume.fieldMapping": "Field Mapping",
    "resume.viewDetail": "View Details",
    "resume.delete": "Delete",
    "resume.profilePending": "Generating your profile…",
    "resume.profilePendingHint": "Takes about 30s, the page will auto-refresh",
    "resume.profileProjects": "Projects",
    "resume.profileIntention": "Career Intention",
    "resume.profileTitle": "Career Profile",
    "resume.monthsUnit": " mo",
    "resume.parseResult": "Resume Parse Result",
    "resume.structuredFields": "Structured Fields",
    "resume.aiExtracted": "AI Extracted",
    "resume.name": "Name",
    "resume.email": "Email",
    "resume.phone": "Phone",
    "resume.location": "Location",
    "resume.education": "Education",
    "resume.experience": "Experience",
    "resume.skills": "Skills",
    "resume.basicInfo": "Basic Info",
    "resume.configureMapping": "Configure Field Mapping",
    "resume.loginFirst": "Please login first",
    "resume.uploadFailed": "Upload failed",
    "resume.uploadFailedRetry": "Upload failed, please try again",
    "resume.deleteConfirm": "Are you sure you want to delete this resume? This action cannot be undone.",
    "resume.deleteFailed": "Delete failed",
    "resume.deleteFailedRetry": "Delete failed, please try again",
    "resume.extractSuccess": "Fields extracted successfully!",
    "resume.extractFailed": "Extract failed",
    "resume.extractFailedRetry": "Extract failed, please try again",
    // AI Match Page
    "aiMatch.title": "AI Job Match",
    "aiMatch.subtitle": "AI analyzes your resume and recommends the best matching jobs",
    "aiMatch.startMatch": "Start Matching",
    "aiMatch.startMatchDesc": "Select a resume and AI will analyze your skills and experience to match the best jobs",
    "aiMatch.selectResume": "Select Resume",
    "aiMatch.selectResumePlaceholder": "Select a resume to match",
    "aiMatch.region": "Region",
    "aiMatch.direction": "Direction",
    "aiMatch.noOptions": "No options",
    "aiMatch.clearAll": "Clear all",
    "aiMatch.matching": "Matching...",
    "aiMatch.startAiMatch": "Start AI Match",
    "aiMatch.selected": "Selected:",
    "aiMatch.analyzing": "Analyzing resume and matching jobs...",
    "aiMatch.matchResults": "Match Results",
    "aiMatch.recommendations": " recommendations",
    "aiMatch.total": "",
    "aiMatch.matchScore": "Match Score",
    "aiMatch.scoreHigh": "High Match",
    "aiMatch.scoreMedium": "Medium Match",
    "aiMatch.scoreLow": "Low Match",
    "aiMatch.matchReason": "Match Reason",
    "aiMatch.suggestions": "Suggestions",
    "aiMatch.optimizeResume": "Optimize Resume",
    "aiMatch.viewJob": "View Job",
    "aiMatch.emptyTitle": "Select a resume to start matching",
    "aiMatch.emptyDesc": "AI will analyze your resume and recommend the best job opportunities based on job requirements",
    // ATS Optimize Page
    "optimize.title": "ATS Resume Optimization",
    "optimize.subtitle": "Optimize your resume for ATS systems to improve pass rate and visibility",
    "optimize.history": "Optimization History",
    "optimize.english": "EN",
    "optimize.chinese": "CN",
    "optimize.settings": "Optimization Settings",
    "optimize.settingsDesc": "Select a resume and set the target position, AI will optimize the resume content accordingly",
    "optimize.selectResume": "Select Resume",
    "optimize.selectResumePlaceholder": "Select a resume to optimize",
    "optimize.targetCompany": "Target Company (optional)",
    "optimize.targetCompanyPlaceholder": "e.g. Google, Apple...",
    "optimize.searchJdTitle": "Fetch job description and requirements from the web",
    "optimize.targetPosition": "Target Position",
    "optimize.targetPositionPlaceholder": "e.g. Software Engineer...",
    "optimize.targetRegion": "Target Region",
    "optimize.regionUs": "United States",
    "optimize.regionUk": "United Kingdom",
    "optimize.regionSg": "Singapore",
    "optimize.regionHk": "Hong Kong",
    "optimize.regionAu": "Australia",
    "optimize.regionCa": "Canada",
    "optimize.regionEu": "Europe",
    "optimize.regionCn": "Mainland China",
    "optimize.regionJp": "Japan",
    "optimize.optimizing": "Optimizing...",
    "optimize.startOptimize": "Start Optimization",
    "optimize.clearJd": "Clear JD",
    "optimize.jdLabel": "Job Description (optional)",
    "optimize.jdHint": "Paste the target job description and AI will optimize accordingly",
    "optimize.jdPlaceholder": "Paste the job description here...\n\nExample:\nWe are looking for a Software Engineer who is proficient in Python, JavaScript, and cloud technologies...\nRequirements:\n- 3+ years of experience in full-stack development\n- Strong understanding of REST APIs\n- Experience with AWS or Azure",
    "optimize.jdSet": "Job Description Set",
    "optimize.jdSetDesc": "AI will optimize based on the following job requirements",
    "optimize.suggestionsTitle": "Suggestions from AI Job Match",
    "optimize.optimizingProgress": "AI is optimizing your resume...",
    "optimize.feature1Title": "Keyword Optimization",
    "optimize.feature1Desc": "Automatically analyze job requirements and add key skill keywords",
    "optimize.feature2Title": "ATS-Friendly Format",
    "optimize.feature2Desc": "Optimize resume format to ensure correct ATS parsing",
    "optimize.feature3Title": "Content Enhancement",
    "optimize.feature3Desc": "Enhance resume descriptions with professional terminology",
    "optimize.tipsTitle": "ATS Optimization Tips",
    "optimize.tip1": "Use standard format: avoid complex tables and images",
    "optimize.tip2": "Keyword matching: study the target JD and use the same terminology",
    "optimize.tip3": "Quantify achievements: show accomplishments with concrete numbers",
    "optimize.tip4": "Clear structure: use standard section headings",
    "optimize.resultTitle": "Resume Optimization Complete",
    "optimize.resultDesc": "AI has optimized your resume based on the target position",
    "optimize.preview": "Preview",
    "optimize.edit": "Edit",
    "optimize.copy": "Copy",
    "optimize.save": "Save",
    "optimize.saved": "Saved",
    "optimize.translating": "Translating...",
    "optimize.translate": "CN/EN Translate",
    "optimize.toChinese": "To Chinese",
    "optimize.toEnglish": "To English",
    "optimize.current": "Current",
    "optimize.generating": "Generating...",
    "optimize.download": "Download Resume",
    "optimize.originalResume": "Original Resume",
    "optimize.optimizedResume": "Optimized Resume",
    "optimize.atsBadge": "ATS Optimized",
    "optimize.alertFillFirst": "Please fill in the target company and position first",
    "optimize.alertJdFailed": "Failed to fetch job description",
    "optimize.alertJdRetry": "Failed to fetch job description, please try again later",
    "optimize.alertWordFailed": "Failed to generate Word document, please try again",
    "optimize.unknownResume": "Unknown resume",
    "optimize.copyName": "Name",
    "optimize.copySummary": "Summary",
    "optimize.copySkills": "Skills",
    "optimize.copyExperience": "Experience",
    "optimize.copyEducation": "Education",
    "optimize.copyProjects": "Projects",
    "optimize.copyCertifications": "Certifications",
    // Showcase Page
    "showcase.title": "Interactive 3D",
    "showcase.description": "Bring your UI to life with beautiful 3D scenes. Create immersive experiences that capture attention and enhance your design.",
    "showcase.clickToEnter": "Click anywhere to enter",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>("en");

  useEffect(() => {
    const savedLocale = localStorage.getItem("locale") as Locale;
    if (savedLocale && ["zh-CN", "zh-TW", "en"].includes(savedLocale)) {
      setLocale(savedLocale);
    }
  }, []);

  const handleSetLocale = (newLocale: Locale) => {
    setLocale(newLocale);
    localStorage.setItem("locale", newLocale);
  };

  const t = (key: string): string => {
    return translations[locale][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale: handleSetLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
