"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Locale = "zh-CN" | "zh-TW" | "en";

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Locale, Record<string, string>> = {
  "zh-CN": {
    // 导航栏
    "nav.home": "首页",
    "nav.features": "功能",
    "nav.more": "更多",
    "nav.jobSearch": "岗位查询",
    "nav.resumeManager": "简历管理",
    "nav.aiMatch": "AI选岗",
    "nav.atsOptimize": "ATS简历优化",
    "nav.applications": "网申管理",
    "nav.autoApplication": "自动网申",
    "nav.admin": "后台管理",
    "nav.login": "登录",
    "nav.getStarted": "登录",
    "nav.logout": "退出",
    // 功能卡片
    "features.title": "核心功能",
    "features.subtitle": "为您的求职之路提供全方位支持",
    "feature1.title": "AI智能选岗",
    "feature1.desc": "基于简历智能匹配岗位，精准推荐最适合的机会。",
    "feature2.title": "ATS简历优化",
    "feature2.desc": "针对ATS系统优化简历格式，提高通过率。",
    "feature3.title": "自动网申填写",
    "feature3.desc": "Chrome扩展自动填充网申表单，节省大量重复填写时间。",
    "feature4.title": "海量岗位资源",
    "feature4.desc": "聚合全球知名企业岗位信息，覆盖科技、金融、咨询等多个行业。",
    "feature5.title": "求职进度追踪",
    "feature5.desc": "实时追踪网申状态，管理求职进度，不错过任何机会。",
    "feature6.title": "AI 模拟面试",
    "feature6.desc": "与 AI 进行模拟面试，获得即时反馈，提升面试表现。",
    // AI 模拟面试页面
    "mockInterview.title": "AI 模拟面试",
    "mockInterview.subtitle": "与 AI 进行真实场景模拟面试，获得即时反馈，提升面试表现",
    "mockInterview.position": "面试岗位",
    "mockInterview.positionPlaceholder": "请输入面试岗位名称",
    "mockInterview.jd": "岗位描述 (JD)",
    "mockInterview.jdPlaceholder": "请粘贴岗位描述，AI 将根据 JD 生成针对性面试问题",
    "mockInterview.difficulty": "面试难度",
    "mockInterview.start": "开始面试",
    "mockInterview.starting": "面试准备中...",
    "mockInterview.easy": "初级",
    "mockInterview.medium": "中级",
    "mockInterview.hard": "高级",
    "mockInterview.interviewer": "AI 面试官",
    "mockInterview.yourAnswer": "你的回答",
    "mockInterview.answerPlaceholder": "请输入你的回答...",
    "mockInterview.submit": "提交回答",
    "mockInterview.submitting": "评估中...",
    "mockInterview.nextQuestion": "下一题",
    "mockInterview.endInterview": "结束面试",
    "mockInterview.feedback": "面试反馈",
    "mockInterview.overallScore": "总体评分",
    "mockInterview.strengths": "你的优势",
    "mockInterview.improvements": "改进建议",
    "mockInterview.sampleAnswers": "参考回答",
    "mockInterview.restart": "重新开始",
    "mockInterview.selectPosition": "请先选择面试岗位",
    "mockInterview.enterAnswer": "请输入你的回答",
    "mockInterview.sessionExpired": "面试会话已过期，请重新开始",
    "mockInterview.feedbackError": "获取反馈失败，请重试",
    // FAQs
    "faqs.title": "常见问题",
    "faqs.subtitle": "快速解答关于Rising Path平台的常见问题",
    "faqs.contact": "找不到答案？联系我们的",
    "faqs.contactLink": "客服团队",
    "faq1.q": "Rising Path是什么？",
    "faq1.a": "Rising Path是一个专为海外留学生打造的一站式求职平台，提供岗位查询、AI选岗、简历优化、自动网申等功能，帮助您高效求职。",
    "faq2.q": "如何使用访问码？",
    "faq2.a": "访问码是进入平台的凭证。在首页点击任意功能卡片，输入有效的访问码即可进入对应功能页面。每个访问码对应独立的用户空间。",
    "faq3.q": "支持哪些地区和行业？",
    "faq3.a": "我们覆盖全球主要留学目的地国家，包括美国、英国、加拿大、澳大利亚等。行业涵盖科技、金融、咨询、医疗等多个领域。",
    "faq4.q": "简历数据安全吗？",
    "faq4.a": "我们采用企业级数据加密和隔离技术，每个访问码的数据完全独立存储，确保您的信息安全。",
    "faq5.q": "如何联系客服？",
    "faq5.a": "您可以通过平台内的客服系统或发送邮件至support@risingpath.com联系我们的客服团队，我们会在24小时内回复。",
    // 平台介绍
    "intro.greeting": "亲爱的同学：",
    "intro.p1": "当几乎所有机构都在把自己包装成精致的都市丽人，穿西装在高档写字楼里谈「赋能」「赛道」时，我们选择一头扎进泥土里。泥土里有被折叠的真实信息——那些机构不愿明说「这个岗位今年只招三人」的数据；那些被包装成「独家」其实公开可查的链接；那些用漂亮话掩盖的冰冷但有用的行业真相。泥土里也有被消费升级和求职焦虑抛弃的普通学生——他们不是不想花十几万块买安心，是花不起；不是不想被精心服务，是发现所谓精心服务最终只是为了把自己塞进更贵的链条。",
    "intro.p2": "对于一个清醒意识到求职重要性的同学来说，能花极低的成本解决最直接的问题，就是最大的进步。",
    "intro.p3": "我们管这叫「决策降级」——不是消费降级，是把选择权、评判权、止损权，一样一样还给你。以前做一个求职决策，先被销售教育两小时，再被合同困住半年，最后被维权消耗一个月。现在，你来决定值不值，你来决定要不要继续，你来决定什么时候转身就走。",
    "intro.p4": "我们只负责一件事：把真正有用的工具，做到足够便宜、足够直接、足够没废话。",
    // 访问码页面
    "accessCode.title": "欢迎使用 Rising Path",
    "accessCode.subtitle": "输入您的专属访问码，开启智能求职之旅。AI 智能选岗、简历优化、自动网申，助力海外留学生拿到理想 Offer。",
    "accessCode.button": "进入平台",
    "accessCode.placeholder": "请输入访问码",
    "accessCode.error.empty": "请输入访问码",
    "accessCode.error.invalid": "访问码无效或已过期",
    "accessCode.error.failed": "验证失败，请稍后重试",
    // 功能页面
    "page.jobs.title": "岗位查询",
    "page.jobs.subtitle": "浏览海量岗位，找到最适合的机会",
    "page.resume.title": "简历管理",
    "page.resume.subtitle": "上传和管理您的简历",
    "page.aiMatch.title": "AI 智能选岗",
    "page.aiMatch.subtitle": "基于简历智能匹配岗位，精准推荐最适合的机会",
    "page.optimize.title": "ATS 简历优化",
    "page.optimize.subtitle": "针对 ATS 系统优化简历格式，提高通过率",
    "page.applications.title": "网申管理",
    "page.applications.subtitle": "实时追踪网申状态，管理求职进度",
    "page.fieldMappings.title": "自动网申",
    "page.fieldMappings.subtitle": "学习记录网申字段，自动填写表单",
    "page.loading": "加载中...",
    "page.error": "加载失败，请稍后重试",
    "page.noData": "暂无数据",
    "page.submit": "提交",
    "page.cancel": "取消",
    "page.save": "保存",
    "page.delete": "删除",
    "page.edit": "编辑",
    "page.add": "添加",
    "page.search": "搜索",
    "page.filter": "筛选",
    "page.all": "全部",
    "page.back": "返回",
    "page.next": "下一步",
    "page.previous": "上一步",
    "page.confirm": "确认",
    "page.close": "关闭",
    // 岗位查询页面
    "jobs.filter": "筛选",
    "jobs.region": "地区",
    "jobs.direction": "方向",
    "jobs.audience": "受众",
    "jobs.clearAll": "清除全部",
    "jobs.noOptions": "暂无选项",
    "jobs.loading": "加载中...",
    "jobs.noJobs": "暂无符合条件的岗位，请调整筛选条件",
    "jobs.active": "可投递",
    "jobs.inactive": "不可投递",
    "jobs.sponsor": "Sponsor",
    "jobs.noSponsor": "无Sponsor",
    "jobs.add": "添加",
    "jobs.added": "已添加",
    "jobs.viewDetail": "查看详情",
    "jobs.originalLink": "原链接",
    "jobs.foundJobs": "共找到",
    "jobs.jobsUnit": "个岗位",
    "jobs.loginFirst": "请先登录",
    "jobs.addFailed": "添加失败",
    "jobs.addFailedRetry": "添加失败，请重试",
    "jobs.searchPlaceholder": "搜索岗位名称或公司...",
    // 简历管理页面
    "resume.title": "简历管理",
    "resume.subtitle": "上传、管理你的简历，支持智能解析",
    "resume.uploaded": "已上传",
    "resume.resumesUnit": "份简历",
    "resume.nextStep": "你可以基于简历进行下一步操作",
    "resume.aiMatch": "AI选岗",
    "resume.optimize": "优化简历",
    "resume.noResume": "还没有简历？上传后可以享受更多服务",
    "resume.feature.aiMatch": "AI智能选岗",
    "resume.feature.optimize": "优化简历ATS",
    "resume.feature.autoApply": "一键填写网申",
    "resume.upload.title": "上传简历",
    "resume.upload.description": "支持 PDF、Word (.docx)、TXT 格式，系统将自动解析提取关键信息",
    "resume.upload.button": "上传简历",
    "resume.upload.uploading": "上传中...",
    "resume.upload.hint": "支持 PDF、Word (.docx)、TXT 格式，系统将自动提取姓名、联系方式、教育经历、工作经验、技能等信息",
    "resume.upload.selected": "已选择",
    "resume.upload.parsing": "正在上传并解析...",
    "resume.upload.complete": "上传完成！",
    "resume.myResumes": "我的简历",
    "resume.refresh": "刷新列表",
    "resume.loading": "加载中...",
    "resume.noResumes": "暂无简历，上传你的第一份简历吧",
    "resume.parsing": "解析中...",
    "resume.extractFields": "提取字段",
    "resume.extracting": "提取中",
    "resume.extracted": "已提取",
    "resume.translate": "翻译",
    "resume.translating": "翻译中",
    "resume.fieldMapping": "字段映射",
    "resume.viewDetail": "查看详情",
    "resume.parseResult": "简历解析结果",
    "resume.structuredFields": "结构化字段",
    "resume.aiExtracted": "AI 提取",
    "resume.name": "姓名",
    "resume.email": "邮箱",
    "resume.phone": "电话",
    "resume.location": "地址",
    "resume.education": "教育背景",
    "resume.experience": "工作经历",
    "resume.skills": "技能标签",
    "resume.basicInfo": "基本信息",
    "resume.configureMapping": "配置字段映射",
    "resume.loginFirst": "请先登录",
    "resume.uploadFailed": "上传失败",
    "resume.uploadFailedRetry": "上传失败，请重试",
    "resume.deleteConfirm": "确定要删除这份简历吗？此操作不可撤销。",
    "resume.deleteFailed": "删除失败",
    "resume.deleteFailedRetry": "删除失败，请重试",
    "resume.extractSuccess": "字段提取成功！",
    "resume.extractFailed": "提取失败",
    "resume.extractFailedRetry": "提取失败，请重试",
    // 展示页面
    "showcase.title": "Interactive 3D",
    "showcase.description": "Bring your UI to life with beautiful 3D scenes. Create immersive experiences that capture attention and enhance your design.",
    "showcase.clickToEnter": "点击任意处进入",
  },
  "zh-TW": {
    // 導航欄
    "nav.home": "首頁",
    "nav.features": "功能",
    "nav.more": "更多",
    "nav.jobSearch": "崗位查詢",
    "nav.resumeManager": "簡歷管理",
    "nav.aiMatch": "AI選崗",
    "nav.atsOptimize": "ATS簡歷優化",
    "nav.applications": "網申管理",
    "nav.autoApplication": "自動網申",
    "nav.admin": "後台管理",
    "nav.login": "登入",
    "nav.getStarted": "登錄",
    "nav.logout": "退出",
    // 功能卡片
    "features.title": "核心功能",
    "features.subtitle": "為您的求職之路提供全方位支援",
    "feature1.title": "AI智能選崗",
    "feature1.desc": "基於簡歷智能匹配崗位，精準推薦最適合的機會。",
    "feature2.title": "ATS簡歷優化",
    "feature2.desc": "針對ATS系統優化簡歷格式，提高通過率。",
    "feature3.title": "自動網申填寫",
    "feature3.desc": "Chrome擴展自動填充網申表單，節省大量重複填寫時間。",
    "feature4.title": "海量崗位資源",
    "feature4.desc": "聚合全球知名企業崗位資訊，覆蓋科技、金融、諮詢等多個行業。",
    "feature5.title": "求職進度追蹤",
    "feature5.desc": "實時追蹤網申狀態，管理求職進度，不錯過任何機會。",
    "feature6.title": "AI 模擬面試",
    "feature6.desc": "與 AI 進行模擬面試，獲得即時反饋，提升面試表現。",
    // AI 模拟面试页面
    "mockInterview.title": "AI 模擬面試",
    "mockInterview.subtitle": "與 AI 進行真實場景模擬面試，獲得即時反饋，提升面試表現",
    "mockInterview.position": "面試崗位",
    "mockInterview.positionPlaceholder": "請輸入面試崗位名稱",
    "mockInterview.jd": "崗位描述 (JD)",
    "mockInterview.jdPlaceholder": "請粘貼崗位描述，AI 將根據 JD 生成針對性面試問題",
    "mockInterview.difficulty": "面試難度",
    "mockInterview.start": "開始面試",
    "mockInterview.starting": "面試準備中...",
    "mockInterview.easy": "初級",
    "mockInterview.medium": "中級",
    "mockInterview.hard": "高級",
    "mockInterview.interviewer": "AI 面試官",
    "mockInterview.yourAnswer": "你的回答",
    "mockInterview.answerPlaceholder": "請輸入你的回答...",
    "mockInterview.submit": "提交回答",
    "mockInterview.submitting": "評估中...",
    "mockInterview.nextQuestion": "下一題",
    "mockInterview.endInterview": "結束面試",
    "mockInterview.feedback": "面試反饋",
    "mockInterview.overallScore": "總體評分",
    "mockInterview.strengths": "你的優勢",
    "mockInterview.improvements": "改進建議",
    "mockInterview.sampleAnswers": "參考回答",
    "mockInterview.restart": "重新開始",
    "mockInterview.selectPosition": "請先選擇面試崗位",
    "mockInterview.enterAnswer": "請輸入你的回答",
    "mockInterview.sessionExpired": "面試會話已過期，請重新開始",
    "mockInterview.feedbackError": "獲取反饋失敗，請重試",
    // FAQs
    "faqs.title": "常見問題",
    "faqs.subtitle": "快速解答關於Rising Path平台的常見問題",
    "faqs.contact": "找不到答案？聯繫我們的",
    "faqs.contactLink": "客服團隊",
    "faq1.q": "Rising Path是什麼？",
    "faq1.a": "Rising Path是一個專為海外留學生打造的一站式求職平台，提供崗位查詢、AI選崗、簡歷優化、自動網申等功能，幫助您高效求職。",
    "faq2.q": "如何使用訪問碼？",
    "faq2.a": "訪問碼是進入平台的憑證。在首頁點擊任意功能卡片，輸入有效的訪問碼即可進入對應功能頁面。每個訪問碼對應獨立的用戶空間。",
    "faq3.q": "支援哪些地區和行業？",
    "faq3.a": "我們覆蓋全球主要留學目的地國家，包括美國、英國、加拿大、澳洲等。行業涵蓋科技、金融、諮詢、醫療等多個領域。",
    "faq4.q": "簡歷數據安全嗎？",
    "faq4.a": "我們採用企業級數據加密和隔離技術，每個訪問碼的數據完全獨立存儲，確保您的資訊安全。",
    "faq5.q": "如何聯繫客服？",
    "faq5.a": "您可以通過平台內的客服系統或發送郵件至support@risingpath.com聯繫我們的客服團隊，我們會在24小時內回覆。",
    // 平台介紹
    "intro.greeting": "親愛的同學：",
    "intro.p1": "當幾乎所有機構都在把自己包裝成精緻的都市麗人，穿西裝在高檔寫字樓裡談「賦能」「賽道」時，我們選擇一頭扎進泥土裡。泥土裡有被摺疊的真實資訊——那些機構不願明說「這個崗位今年只招三人」的數據；那些被包裝成「獨家」其實公開可查的連結；那些用漂亮話掩蓋的冰冷但有用的行業真相。泥土裡也有被消費升級和求職焦慮拋棄的普通學生——他們不是不想花十幾萬塊買安心，是花不起；不是不想被精心服務，是發現所謂精心服務最終只是為了把自己塞進更貴的鏈條。",
    "intro.p2": "對於一個清醒意識到求職重要性的同學來說，能花極低的成本解決最直接的問題，就是最大的進步。",
    "intro.p3": "我們管這叫「決策降級」——不是消費降級，是把選擇權、評判權、止損權，一樣一樣還給你。以前做一個求職決策，先被銷售教育兩小時，再被合同困住半年，最後被維權消耗一個月。現在，你來決定值不值，你來決定要不要繼續，你來決定什麼時候轉身就走。",
    "intro.p4": "我們只負責一件事：把真正有用的工具，做到足夠便宜、足夠直接、足夠沒廢話。",
    // 訪問碼頁面
    "accessCode.title": "歡迎使用 Rising Path",
    "accessCode.subtitle": "輸入您的專屬訪問碼，開啟智能求職之旅。AI 智能選崗、簡歷優化、自動網申，助力海外留學生拿到理想 Offer。",
    "accessCode.button": "進入平台",
    "accessCode.placeholder": "請輸入訪問碼",
    "accessCode.error.empty": "請輸入訪問碼",
    "accessCode.error.invalid": "訪問碼無效或已過期",
    "accessCode.error.failed": "驗證失敗，請稍後重試",
    // 功能頁面
    "page.jobs.title": "崗位查詢",
    "page.jobs.subtitle": "瀏覽海量崗位，找到最適合的機會",
    "page.resume.title": "簡歷管理",
    "page.resume.subtitle": "上傳和管理您的簡歷",
    "page.aiMatch.title": "AI 智能選崗",
    "page.aiMatch.subtitle": "基於簡歷智能匹配崗位，精準推薦最適合的機會",
    "page.optimize.title": "ATS 簡歷優化",
    "page.optimize.subtitle": "針對 ATS 系統優化簡歷格式，提高通過率",
    "page.applications.title": "網申管理",
    "page.applications.subtitle": "實時追蹤網申狀態，管理求職進度",
    "page.fieldMappings.title": "自動網申",
    "page.fieldMappings.subtitle": "學習記錄網申字段，自動填寫表單",
    "page.loading": "加載中...",
    "page.error": "加載失敗，請稍後重試",
    "page.noData": "暫無數據",
    "page.submit": "提交",
    "page.cancel": "取消",
    "page.save": "保存",
    "page.delete": "刪除",
    "page.edit": "編輯",
    "page.add": "添加",
    "page.search": "搜索",
    "page.filter": "篩選",
    "page.all": "全部",
    "page.back": "返回",
    "page.next": "下一步",
    "page.previous": "上一步",
    "page.confirm": "確認",
    "page.close": "關閉",
    // 崗位查詢頁面
    "jobs.filter": "篩選",
    "jobs.region": "地區",
    "jobs.direction": "方向",
    "jobs.audience": "受眾",
    "jobs.clearAll": "清除全部",
    "jobs.noOptions": "暫無選項",
    "jobs.loading": "加載中...",
    "jobs.noJobs": "暫無符合條件的崗位，請調整篩選條件",
    "jobs.active": "可投遞",
    "jobs.inactive": "不可投遞",
    "jobs.sponsor": "Sponsor",
    "jobs.noSponsor": "無Sponsor",
    "jobs.add": "添加",
    "jobs.added": "已添加",
    "jobs.viewDetail": "查看詳情",
    "jobs.originalLink": "原鏈接",
    "jobs.foundJobs": "共找到",
    "jobs.jobsUnit": "個崗位",
    "jobs.loginFirst": "請先登錄",
    "jobs.addFailed": "添加失敗",
    "jobs.addFailedRetry": "添加失敗，請重試",
    "jobs.searchPlaceholder": "搜索崗位名稱或公司...",
    // 簡歷管理頁面
    "resume.title": "簡歷管理",
    "resume.subtitle": "上傳、管理你的簡歷，支持智能解析",
    "resume.uploaded": "已上傳",
    "resume.resumesUnit": "份簡歷",
    "resume.nextStep": "你可以基於簡歷進行下一步操作",
    "resume.aiMatch": "AI選崗",
    "resume.optimize": "優化簡歷",
    "resume.noResume": "還沒有簡歷？上傳後可以享受更多服務",
    "resume.feature.aiMatch": "AI智能選崗",
    "resume.feature.optimize": "優化簡歷ATS",
    "resume.feature.autoApply": "一鍵填寫網申",
    "resume.upload.title": "上傳簡歷",
    "resume.upload.description": "支持 PDF、Word (.docx)、TXT 格式，系統將自動解析提取關鍵信息",
    "resume.upload.button": "上傳簡歷",
    "resume.upload.uploading": "上傳中...",
    "resume.upload.hint": "支持 PDF、Word (.docx)、TXT 格式，系統將自動提取姓名、聯繫方式、教育經歷、工作經驗、技能等信息",
    "resume.upload.selected": "已選擇",
    "resume.upload.parsing": "正在上傳並解析...",
    "resume.upload.complete": "上傳完成！",
    "resume.myResumes": "我的簡歷",
    "resume.refresh": "刷新列表",
    "resume.loading": "加載中...",
    "resume.noResumes": "暫無簡歷，上傳你的第一份簡歷吧",
    "resume.parsing": "解析中...",
    "resume.extractFields": "提取字段",
    "resume.extracting": "提取中",
    "resume.extracted": "已提取",
    "resume.translate": "翻譯",
    "resume.translating": "翻譯中",
    "resume.fieldMapping": "字段映射",
    "resume.viewDetail": "查看詳情",
    "resume.parseResult": "簡歷解析結果",
    "resume.structuredFields": "結構化字段",
    "resume.aiExtracted": "AI 提取",
    "resume.name": "姓名",
    "resume.email": "郵箱",
    "resume.phone": "電話",
    "resume.location": "地址",
    "resume.education": "教育背景",
    "resume.experience": "工作經歷",
    "resume.skills": "技能標籤",
    "resume.basicInfo": "基本信息",
    "resume.configureMapping": "配置字段映射",
    "resume.loginFirst": "請先登錄",
    "resume.uploadFailed": "上傳失敗",
    "resume.uploadFailedRetry": "上傳失敗，請重試",
    "resume.deleteConfirm": "確定要刪除這份簡歷嗎？此操作不可撤銷。",
    "resume.deleteFailed": "刪除失敗",
    "resume.deleteFailedRetry": "刪除失敗，請重試",
    "resume.extractSuccess": "字段提取成功！",
    "resume.extractFailed": "提取失敗",
    "resume.extractFailedRetry": "提取失敗，請重試",
    // 展示頁面
    "showcase.title": "Interactive 3D",
    "showcase.description": "Bring your UI to life with beautiful 3D scenes. Create immersive experiences that capture attention and enhance your design.",
    "showcase.clickToEnter": "點擊任意處進入",
  },
  "en": {
    // Navigation
    "nav.home": "Home",
    "nav.features": "Features",
    "nav.more": "More",
    "nav.jobSearch": "Job Search",
    "nav.resumeManager": "Resume Manager",
    "nav.aiMatch": "AI Match",
    "nav.atsOptimize": "ATS Optimize",
    "nav.applications": "Applications",
    "nav.autoApplication": "Auto Application",
    "nav.admin": "Admin",
    "nav.login": "Log in",
    "nav.getStarted": "Login",
    "nav.logout": "Log out",
    // Features
    "features.title": "Core Features",
    "features.subtitle": "Comprehensive support for your career journey",
    "feature1.title": "AI Job Match",
    "feature1.desc": "Intelligently match jobs based on your resume, recommending the best opportunities.",
    "feature2.title": "ATS Resume Optimize",
    "feature2.desc": "Optimize resume format for ATS systems to improve success rate.",
    "feature3.title": "Auto Application",
    "feature3.desc": "Chrome extension auto-fills application forms, saving time on repetitive tasks.",
    "feature4.title": "Massive Job Resources",
    "feature4.desc": "Aggregates job info from global companies across tech, finance, consulting and more.",
    "feature5.title": "Application Tracking",
    "feature5.desc": "Track application status in real-time, manage your job search progress.",
    "feature6.title": "AI Mock Interview",
    "feature6.desc": "Practice interviews with AI, get instant feedback to improve your performance.",
    // AI Mock Interview Page
    "mockInterview.title": "AI Mock Interview",
    "mockInterview.subtitle": "Practice real-scenario interviews with AI, get instant feedback to improve your performance",
    "mockInterview.position": "Position",
    "mockInterview.positionPlaceholder": "Enter the position name",
    "mockInterview.jd": "Job Description (JD)",
    "mockInterview.jdPlaceholder": "Paste the job description, AI will generate targeted questions based on JD",
    "mockInterview.difficulty": "Difficulty",
    "mockInterview.start": "Start Interview",
    "mockInterview.starting": "Preparing...",
    "mockInterview.easy": "Easy",
    "mockInterview.medium": "Medium",
    "mockInterview.hard": "Hard",
    "mockInterview.interviewer": "AI Interviewer",
    "mockInterview.yourAnswer": "Your Answer",
    "mockInterview.answerPlaceholder": "Enter your answer...",
    "mockInterview.submit": "Submit",
    "mockInterview.submitting": "Evaluating...",
    "mockInterview.nextQuestion": "Next Question",
    "mockInterview.endInterview": "End Interview",
    "mockInterview.feedback": "Feedback",
    "mockInterview.overallScore": "Overall Score",
    "mockInterview.strengths": "Strengths",
    "mockInterview.improvements": "Improvements",
    "mockInterview.sampleAnswers": "Sample Answers",
    "mockInterview.restart": "Restart",
    "mockInterview.selectPosition": "Please select a position first",
    "mockInterview.enterAnswer": "Please enter your answer",
    "mockInterview.sessionExpired": "Session expired, please restart",
    "mockInterview.feedbackError": "Failed to get feedback, please try again",
    // FAQs
    "faqs.title": "Frequently Asked Questions",
    "faqs.subtitle": "Quick answers to common questions about Rising Path platform",
    "faqs.contact": "Can't find the answer? Contact our",
    "faqs.contactLink": "customer support team",
    "faq1.q": "What is Rising Path?",
    "faq1.a": "Rising Path is an all-in-one career platform designed for international students, offering job search, AI matching, resume optimization, and auto-application features.",
    "faq2.q": "How to use access code?",
    "faq2.a": "Access code is your credential to enter the platform. Click any feature card on the homepage and enter a valid access code to access the corresponding feature page.",
    "faq3.q": "Which regions and industries are supported?",
    "faq3.a": "We cover major study abroad destinations including USA, UK, Canada, Australia. Industries include tech, finance, consulting, healthcare and more.",
    "faq4.q": "Is resume data secure?",
    "faq4.a": "We use enterprise-grade encryption and data isolation. Each access code's data is stored independently to ensure your information security.",
    "faq5.q": "How to contact support?",
    "faq5.a": "You can reach our support team through the in-platform support system or email support@risingpath.com. We'll respond within 24 hours.",
    // Platform Introduction
    "intro.greeting": "Dear Student,",
    "intro.p1": "While almost all agencies package themselves as polished urban professionals, wearing suits in fancy office buildings talking about \"empowerment\" and \"market segments,\" we choose to dive straight into the mud. In the mud lies the folded truth — data that agencies won't openly share like \"this position only hires three people this year\"; links that are packaged as \"exclusive\" but are actually publicly available; cold but useful industry truths hidden behind fancy words. The mud also holds ordinary students abandoned by consumption upgrades and job-seeking anxiety — they don't refuse to spend hundreds of thousands for peace of mind, they simply can't afford it; they don't refuse to be carefully served, they just realize that so-called careful service is ultimately just about squeezing them into a more expensive chain.",
    "intro.p2": "For a student who is clearly aware of the importance of job seeking, being able to solve the most direct problems at the lowest cost is the greatest progress.",
    "intro.p3": "We call this \"decision downgrade\" — not consumption downgrade, but returning the right to choose, judge, and cut losses back to you, one by one. Before, making a job-seeking decision meant being educated by sales for two hours, trapped by a contract for six months, and consumed by rights protection for a month. Now, you decide if it's worth it, you decide whether to continue, you decide when to walk away.",
    "intro.p4": "We are only responsible for one thing: making truly useful tools cheap enough, direct enough, and without nonsense.",
    // Access Code Page
    "accessCode.title": "Welcome to Rising Path",
    "accessCode.subtitle": "Enter your exclusive access code to start your intelligent job-seeking journey. AI job matching, resume optimization, and auto-application help international students land their ideal offers.",
    "accessCode.button": "Enter Platform",
    "accessCode.placeholder": "Enter access code",
    "accessCode.error.empty": "Please enter access code",
    "accessCode.error.invalid": "Invalid or expired access code",
    "accessCode.error.failed": "Verification failed, please try again later",
    // Feature Pages
    "page.jobs.title": "Job Search",
    "page.jobs.subtitle": "Browse massive job listings and find the best opportunities",
    "page.resume.title": "Resume Manager",
    "page.resume.subtitle": "Upload and manage your resumes",
    "page.aiMatch.title": "AI Job Match",
    "page.aiMatch.subtitle": "Intelligently match jobs based on your resume, recommending the best opportunities",
    "page.optimize.title": "ATS Resume Optimize",
    "page.optimize.subtitle": "Optimize resume format for ATS systems to improve success rate",
    "page.applications.title": "Applications",
    "page.applications.subtitle": "Track application status in real-time, manage your job search progress",
    "page.fieldMappings.title": "Auto Application",
    "page.fieldMappings.subtitle": "Learn and record application fields, auto-fill forms",
    "page.loading": "Loading...",
    "page.error": "Failed to load, please try again later",
    "page.noData": "No data",
    "page.submit": "Submit",
    "page.cancel": "Cancel",
    "page.save": "Save",
    "page.delete": "Delete",
    "page.edit": "Edit",
    "page.add": "Add",
    "page.search": "Search",
    "page.filter": "Filter",
    "page.all": "All",
    "page.back": "Back",
    "page.next": "Next",
    "page.previous": "Previous",
    "page.confirm": "Confirm",
    "page.close": "Close",
    // Jobs Page
    "jobs.filter": "Filter",
    "jobs.region": "Region",
    "jobs.direction": "Direction",
    "jobs.audience": "Audience",
    "jobs.clearAll": "Clear All",
    "jobs.noOptions": "No options",
    "jobs.loading": "Loading...",
    "jobs.noJobs": "No jobs found. Please adjust your filters.",
    "jobs.active": "Active",
    "jobs.inactive": "Inactive",
    "jobs.sponsor": "Sponsor",
    "jobs.noSponsor": "No Sponsor",
    "jobs.add": "Add",
    "jobs.added": "Added",
    "jobs.viewDetail": "View Details",
    "jobs.originalLink": "Original Link",
    "jobs.foundJobs": "Found",
    "jobs.jobsUnit": "jobs",
    "jobs.loginFirst": "Please login first",
    "jobs.addFailed": "Failed to add",
    "jobs.addFailedRetry": "Failed to add, please try again",
    "jobs.searchPlaceholder": "Search job title or company...",
    // Resume Page
    "resume.title": "Resume Manager",
    "resume.subtitle": "Upload and manage your resumes with AI parsing",
    "resume.uploaded": "Uploaded",
    "resume.resumesUnit": "resumes",
    "resume.nextStep": "You can proceed with the next steps based on your resume",
    "resume.aiMatch": "AI Match",
    "resume.optimize": "Optimize",
    "resume.noResume": "No resume yet? Upload to unlock more features",
    "resume.feature.aiMatch": "AI Job Match",
    "resume.feature.optimize": "ATS Optimize",
    "resume.feature.autoApply": "Auto Apply",
    "resume.upload.title": "Upload Resume",
    "resume.upload.description": "Supports PDF, Word (.docx), TXT formats. System will automatically parse key information",
    "resume.upload.button": "Upload Resume",
    "resume.upload.uploading": "Uploading...",
    "resume.upload.hint": "Supports PDF, Word (.docx), TXT formats. System will extract name, contact, education, experience, skills, etc.",
    "resume.upload.selected": "Selected",
    "resume.upload.parsing": "Uploading and parsing...",
    "resume.upload.complete": "Upload complete!",
    "resume.myResumes": "My Resumes",
    "resume.refresh": "Refresh",
    "resume.loading": "Loading...",
    "resume.noResumes": "No resumes yet. Upload your first resume!",
    "resume.parsing": "Parsing...",
    "resume.extractFields": "Extract Fields",
    "resume.extracting": "Extracting",
    "resume.extracted": "Extracted",
    "resume.translate": "Translate",
    "resume.translating": "Translating",
    "resume.fieldMapping": "Field Mapping",
    "resume.viewDetail": "View Details",
    "resume.parseResult": "Resume Parse Result",
    "resume.structuredFields": "Structured Fields",
    "resume.aiExtracted": "AI Extracted",
    "resume.name": "Name",
    "resume.email": "Email",
    "resume.phone": "Phone",
    "resume.location": "Location",
    "resume.education": "Education",
    "resume.experience": "Experience",
    "resume.skills": "Skills",
    "resume.basicInfo": "Basic Info",
    "resume.configureMapping": "Configure Field Mapping",
    "resume.loginFirst": "Please login first",
    "resume.uploadFailed": "Upload failed",
    "resume.uploadFailedRetry": "Upload failed, please try again",
    "resume.deleteConfirm": "Are you sure you want to delete this resume? This action cannot be undone.",
    "resume.deleteFailed": "Delete failed",
    "resume.deleteFailedRetry": "Delete failed, please try again",
    "resume.extractSuccess": "Fields extracted successfully!",
    "resume.extractFailed": "Extract failed",
    "resume.extractFailedRetry": "Extract failed, please try again",
    // Showcase Page
    "showcase.title": "Interactive 3D",
    "showcase.description": "Bring your UI to life with beautiful 3D scenes. Create immersive experiences that capture attention and enhance your design.",
    "showcase.clickToEnter": "Click anywhere to enter",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>("en");

  useEffect(() => {
    const savedLocale = localStorage.getItem("locale") as Locale;
    if (savedLocale && ["zh-CN", "zh-TW", "en"].includes(savedLocale)) {
      setLocale(savedLocale);
    }
  }, []);

  const handleSetLocale = (newLocale: Locale) => {
    setLocale(newLocale);
    localStorage.setItem("locale", newLocale);
  };

  const t = (key: string): string => {
    return translations[locale][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale: handleSetLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
