server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name _;

  root /www/wwwroot/liorvix-cn;
  index index.html;

  charset utf-8;
  client_max_body_size 8m;

  location / {
    try_files $uri $uri/ =404;
  }

  location = /healthz {
    default_type text/plain;
    return 200 "ok\n";
  }
}
