'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Archive, BriefcaseBusiness, ChevronDown, Clock3, Loader2, MapPin, PenLine, Send, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { apiFetch } from '@/lib/api-client';
import { APPLICATION_STATUSES, APPLICATION_STATUS_LABELS, type ApplicationStatus } from '@/lib/application-status';
import { useLanguage, type Locale } from '@/lib/language-context';

interface Application { id: number; job_id: number; resume_id: number | null; status: ApplicationStatus; submitted_at: string | null; created_at: string; jobs: { title: string; company: string; region: string; direction: string; } | null; resumes: { file_name: string; } | null; }

const copy: Record<Locale, Record<string, string>> = {
  'zh-CN': { total: '全部', list: '申请记录', loading: '加载中…', empty: '还没有申请记录', emptyHint: '从岗位详情或工作台开始一次网申。', jobs: '浏览岗位', created: '创建于', submitted: '投递于', optimize: '优化简历', detail: '查看岗位', delete: '删除', deleteConfirm: '确定要删除这条网申记录吗？', deleteFailed: '删除失败，请重试', updateFailed: '更新状态失败，请重试', unknownRole: '未知岗位', unknownCompany: '未知公司' },
  'zh-TW': { total: '全部', list: '申請記錄', loading: '載入中…', empty: '還沒有申請記錄', emptyHint: '從職位詳情或工作台開始一次網申。', jobs: '瀏覽職位', created: '建立於', submitted: '投遞於', optimize: '優化履歷', detail: '查看職位', delete: '刪除', deleteConfirm: '確定要刪除這條網申記錄嗎？', deleteFailed: '刪除失敗，請重試', updateFailed: '更新狀態失敗，請重試', unknownRole: '未知職位', unknownCompany: '未知公司' },
  en: { total: 'All', list: 'Applications', loading: 'Loading…', empty: 'No applications yet', emptyHint: 'Start an application from a role page or your workspace.', jobs: 'Browse roles', created: 'Created', submitted: 'Submitted', optimize: 'Tailor resume', detail: 'View role', delete: 'Delete', deleteConfirm: 'Delete this application record?', deleteFailed: 'Could not delete the application. Please try again.', updateFailed: 'Could not update the status. Please try again.', unknownRole: 'Unknown role', unknownCompany: 'Unknown company' },
};

function formatDate(value: string | null, locale: Locale) { if (!value) return ''; return new Intl.DateTimeFormat(locale === 'zh-CN' ? 'zh-CN' : locale === 'zh-TW' ? 'zh-TW' : 'en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)); }

export default function ApplicationList() {
  const { locale } = useLanguage(); const c = copy[locale];
  const [applications, setApplications] = useState<Application[]>([]); const [loading, setLoading] = useState(true); const [filter, setFilter] = useState<'all' | ApplicationStatus>('all'); const [mutatingIds, setMutatingIds] = useState<Set<number>>(new Set());
  const setMutating = (id: number, active: boolean) => setMutatingIds((current) => { const next = new Set(current); if (active) next.add(id); else next.delete(id); return next; });
  const fetchApplications = useCallback(async () => { setLoading(true); try { const response = await apiFetch('/api/applications'); const data = await response.json(); if (!response.ok) throw new Error(data.error); setApplications(data.applications || []); } catch (error) { console.error('Failed to fetch applications:', error); } finally { setLoading(false); } }, []);
  useEffect(() => { void fetchApplications(); }, [fetchApplications]);
  const counts = useMemo(() => { const base = { total: applications.length, pending: 0, filling: 0, submitted: 0, closed: 0 }; applications.forEach((app) => { base[app.status] += 1; }); return base; }, [applications]);
  const filtered = useMemo(() => filter === 'all' ? applications : applications.filter((app) => app.status === filter), [applications, filter]);
  const remove = async (id: number) => { if (!window.confirm(c.deleteConfirm) || mutatingIds.has(id)) return; setMutating(id, true); try { const response = await apiFetch(`/api/applications/${id}`, { method: 'DELETE' }); if (!response.ok) throw new Error(); setApplications((current) => current.filter((app) => app.id !== id)); } catch { window.alert(c.deleteFailed); } finally { setMutating(id, false); } };
  const updateStatus = async (id: number, status: ApplicationStatus) => { if (mutatingIds.has(id)) return; setMutating(id, true); try { const response = await apiFetch(`/api/applications/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); const data = await response.json(); if (!response.ok || !data.application) throw new Error(); setApplications((current) => current.map((app) => app.id === id ? { ...app, status: data.application.status, submitted_at: data.application.submitted_at || app.submitted_at } : app)); } catch { window.alert(c.updateFailed); } finally { setMutating(id, false); } };
  return <div className="space-y-5"><div className="flex flex-wrap gap-2">{([{ key: 'all', label: c.total, count: counts.total }, ...APPLICATION_STATUSES.map((status) => ({ key: status, label: APPLICATION_STATUS_LABELS[status][locale === 'en' ? 'en' : locale === 'zh-TW' ? 'zh' : 'zh'], count: counts[status] }))] as Array<{ key: 'all' | ApplicationStatus; label: string; count: number }>).map((item) => <button key={item.key} type="button" onClick={() => setFilter(item.key)} className={`rounded-md px-3 py-1.5 text-sm transition-colors ${filter === item.key ? 'bg-primary text-primary-foreground' : 'border bg-background text-muted-foreground hover:bg-muted'}`}>{item.label} <span className="ml-1 opacity-70">{item.count}</span></button>)}</div><section className="overflow-hidden rounded-lg border bg-card"><div className="flex items-center justify-between border-b px-5 py-3.5"><h2 className="text-sm font-semibold">{c.list}</h2><span className="text-xs text-muted-foreground">{filtered.length}</span></div>{loading ? <div className="py-16 text-center text-sm text-muted-foreground"><Loader2 className="mx-auto mb-3 h-6 w-6 animate-spin" />{c.loading}</div> : filtered.length === 0 ? <div className="px-5 py-16 text-center"><BriefcaseBusiness className="mx-auto mb-4 h-9 w-9 text-muted-foreground/50" /><p className="text-sm font-medium">{c.empty}</p><p className="mt-1 text-sm text-muted-foreground">{c.emptyHint}</p><Button asChild size="sm" className="mt-5"><Link href="/jobs">{c.jobs}</Link></Button></div> : <div className="divide-y">{filtered.map((app) => <ApplicationRow key={app.id} app={app} locale={locale} c={c} busy={mutatingIds.has(app.id)} onStatusChange={updateStatus} onDelete={remove} />)}</div>}</section></div>;
}

function ApplicationRow({ app, locale, c, busy, onStatusChange, onDelete }: { app: Application; locale: Locale; c: Record<string, string>; busy: boolean; onStatusChange: (id: number, status: ApplicationStatus) => void; onDelete: (id: number) => void }) {
  const labels = APPLICATION_STATUS_LABELS[app.status]; const label = labels[locale === 'en' ? 'en' : 'zh']; const Icon = app.status === 'submitted' ? Send : app.status === 'filling' ? PenLine : app.status === 'closed' ? Archive : Clock3;
  return <article className="flex flex-col gap-4 px-5 py-4 transition-colors hover:bg-muted/30 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex min-w-0 flex-wrap items-center gap-x-2 gap-y-1"><h3 className="truncate text-sm font-semibold">{app.jobs?.title || c.unknownRole}</h3><span className="text-sm text-muted-foreground">{app.jobs?.company || c.unknownCompany}</span></div><div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1.5 text-xs text-muted-foreground"><DropdownMenu><DropdownMenuTrigger asChild><button type="button" disabled={busy} className="inline-flex items-center gap-1 rounded-md border bg-background px-2 py-1 text-foreground transition-colors hover:bg-muted disabled:opacity-50"><Icon className="h-3 w-3 text-primary" />{label}<ChevronDown className="h-3 w-3 text-muted-foreground" /></button></DropdownMenuTrigger><DropdownMenuContent align="start">{APPLICATION_STATUSES.map((status) => <DropdownMenuItem key={status} disabled={busy} onClick={() => onStatusChange(app.id, status)}>{APPLICATION_STATUS_LABELS[status][locale === 'en' ? 'en' : 'zh']}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>{app.jobs?.region && <span className="inline-flex items-center gap-1"><MapPin className="h-3 w-3" />{app.jobs.region}</span>}<span>{c.created} {formatDate(app.created_at, locale)}</span>{app.submitted_at && <span>{c.submitted} {formatDate(app.submitted_at, locale)}</span>}</div></div><div className="flex shrink-0 items-center gap-2"><Button asChild variant="outline" size="sm" className="h-8"><Link href={`/optimize?jobId=${app.job_id}&company=${encodeURIComponent(app.jobs?.company || '')}&position=${encodeURIComponent(app.jobs?.title || '')}&region=${encodeURIComponent(app.jobs?.region || '')}${app.resume_id ? `&resumeId=${app.resume_id}` : ''}`}>{c.optimize}</Link></Button><Button asChild variant="ghost" size="sm" className="h-8"><Link href={`/jobs/${app.job_id}`}>{c.detail}</Link></Button><Button type="button" variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:bg-destructive/10 hover:text-destructive" aria-label={c.delete} title={c.delete} disabled={busy} onClick={() => onDelete(app.id)}>{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Trash2 className="h-4 w-4" />}</Button></div></article>;
}
