#!/usr/bin/env bash
set -Eeuo pipefail

# Run this script on the production server from /opt/liorvix after the release
# files and a production-only .env.local have been placed there.
APP_DIR="${APP_DIR:-/opt/liorvix}"
SERVICE_NAME="${SERVICE_NAME:-liorvix}"

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run this script with sudo so it can install and restart the systemd service." >&2
  exit 1
fi

cd "$APP_DIR"
APP_USER="${APP_USER:-$(stat -c '%U' "$APP_DIR")}"

if ! id "$APP_USER" >/dev/null 2>&1; then
  echo "Deployment user does not exist: $APP_USER" >&2
  exit 1
fi

if [[ ! -f .env.local ]]; then
  echo "Missing $APP_DIR/.env.local" >&2
  exit 1
fi

required_vars=(
  AUTH_SITE_URL
  SUPABASE_URL
  SUPABASE_ANON_KEY
  SUPABASE_SERVICE_ROLE_KEY
  SUPABASE_DB_URL
  SUPABASE_RESUME_BUCKET
  ADMIN_SESSION_SECRET
  ADMIN_BOOTSTRAP_PASSWORD
  DASHSCOPE_API_KEY
)

for name in "${required_vars[@]}"; do
  if ! grep -qE "^${name}=.+" .env.local; then
    echo "Missing required environment variable: ${name}" >&2
    exit 1
  fi
done

PNPM_VERSION="${PNPM_VERSION:-9.0.0}"
corepack enable
corepack prepare "pnpm@${PNPM_VERSION}" --activate
PNPM_CMD="corepack pnpm"
chown -R "$APP_USER":"$APP_USER" "$APP_DIR"
# pnpm 9 can reject a lockfile generated by newer pnpm versions when workspace
# overrides are present. Keep the package versions pinned by the lockfile while
# allowing pnpm to reconcile its metadata before building.
runuser -u "$APP_USER" -- bash -lc "cd '$APP_DIR' && $PNPM_CMD install --no-frozen-lockfile --prod=false"
runuser -u "$APP_USER" -- bash -lc "cd '$APP_DIR' && $PNPM_CMD run db:migrate:admin"
runuser -u "$APP_USER" -- bash -lc "cd '$APP_DIR' && $PNPM_CMD run build"

sed "s/__APP_USER__/${APP_USER}/g" deploy/systemd/liorvix.service | sudo install -m 0644 /dev/stdin "/etc/systemd/system/${SERVICE_NAME}.service"
sudo systemctl daemon-reload
# The web process owns the bounded background worker. Disable legacy external
# timers so the same feed and maintenance work is not scheduled twice.
for timer in liorvix-jobs-incremental.timer liorvix-jobs-maintenance.timer liorvix-jobs-reconcile.timer; do
  sudo systemctl disable --now "$timer" 2>/dev/null || true
done
sudo systemctl enable "$SERVICE_NAME"
sudo systemctl restart "$SERVICE_NAME"
sudo systemctl --no-pager --full status "$SERVICE_NAME"

health_ok="false"
for attempt in $(seq 1 30); do
  if curl --fail --silent --show-error --max-time 5 http://127.0.0.1:5000/api/health; then
    health_ok="true"
    echo
    break
  fi
  sleep 1
done

if [[ "$health_ok" != "true" ]]; then
  echo "Health check failed after waiting for the service to start." >&2
  exit 1
fi

echo "Release completed successfully."
