begin;

-- Stage 2: make resume processing observable and keep immutable profile snapshots.
alter table if exists public.resumes
  add column if not exists processing_status text not null default 'uploaded',
  add column if not exists processing_stage text not null default 'queued',
  add column if not exists processing_error text,
  add column if not exists processing_attempts integer not null default 0,
  add column if not exists processing_started_at timestamptz,
  add column if not exists processing_finished_at timestamptz,
  add column if not exists profile_version integer not null default 0,
  add column if not exists profile_confirmed_at timestamptz,
  add column if not exists profile_confirmed_by uuid references auth.users(id) on delete set null,
  add column if not exists profile_evidence jsonb not null default '{}'::jsonb,
  add column if not exists profile_confidence jsonb not null default '{}'::jsonb;

alter table if exists public.resumes
  drop constraint if exists resumes_processing_status_check,
  drop constraint if exists resumes_processing_stage_check,
  drop constraint if exists resumes_processing_attempts_check,
  drop constraint if exists resumes_profile_version_check;

alter table if exists public.resumes
  add constraint resumes_processing_status_check check (
    processing_status in (
      'uploaded',
      'extracting_text',
      'extracting_profile',
      'deriving_segmentation',
      'needs_confirmation',
      'ready',
      'failed'
    )
  ),
  add constraint resumes_processing_stage_check check (
    processing_stage in (
      'queued',
      'text_extraction',
      'profile_extraction',
      'segmentation',
      'confirmation',
      'complete',
      'error'
    )
  ),
  add constraint resumes_processing_attempts_check check (processing_attempts >= 0),
  add constraint resumes_profile_version_check check (profile_version >= 0);

-- Existing rows have no versioned confirmation record. Force an explicit
-- reconfirmation instead of treating legacy JSON as a current decision.
update public.resumes
set processing_status = case
      when coalesce(parsed_content, '') like '简历解析失败%' then 'failed'
      when profile is not null and segmentation is not null then 'needs_confirmation'
      else 'uploaded'
    end,
    processing_stage = case
      when coalesce(parsed_content, '') like '简历解析失败%' then 'error'
      when profile is not null and segmentation is not null then 'confirmation'
      else 'queued'
    end,
    processing_error = case
      when coalesce(parsed_content, '') like '简历解析失败%' then parsed_content
      else null
    end,
    profile_version = case
      when profile is not null and segmentation is not null then 1
      else 0
    end,
    segmentation_confirmed = false,
    profile_confirmed_at = null,
    profile_confirmed_by = null
where true;

create table if not exists public.resume_profile_versions (
  id bigint generated by default as identity primary key,
  resume_id integer not null references public.resumes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  version integer not null,
  source text not null,
  profile jsonb not null default '{}'::jsonb,
  segmentation jsonb not null default '{}'::jsonb,
  overrides jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '{}'::jsonb,
  confidence jsonb not null default '{}'::jsonb,
  status text not null default 'draft',
  confirmed_at timestamptz,
  confirmed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint resume_profile_versions_version_check check (version > 0),
  constraint resume_profile_versions_source_check check (source in ('initial_parse', 'reparse', 'user_edit', 'legacy_import')),
  constraint resume_profile_versions_status_check check (status in ('draft', 'confirmed', 'superseded')),
  unique (resume_id, version)
);

create index if not exists resumes_processing_status_idx on public.resumes(processing_status);
create index if not exists resumes_profile_version_idx on public.resumes(profile_version);
create index if not exists resume_profile_versions_resume_id_idx on public.resume_profile_versions(resume_id);
create index if not exists resume_profile_versions_user_id_idx on public.resume_profile_versions(user_id);
create index if not exists resume_profile_versions_status_idx on public.resume_profile_versions(status);

-- Keep one draft snapshot for legacy records that already have a usable profile.
insert into public.resume_profile_versions (
  resume_id,
  user_id,
  version,
  source,
  profile,
  segmentation,
  overrides,
  evidence,
  confidence,
  status
)
select
  id,
  user_id,
  1,
  'legacy_import',
  profile,
  segmentation,
  coalesce(segmentation_overrides, '{}'::jsonb),
  coalesce(profile_evidence, '{}'::jsonb),
  coalesce(profile_confidence, '{}'::jsonb),
  'draft'
from public.resumes
where user_id is not null
  and profile is not null
  and segmentation is not null
on conflict (resume_id, version) do nothing;

alter table public.resume_profile_versions enable row level security;

drop policy if exists resume_profile_versions_owner_all on public.resume_profile_versions;
create policy resume_profile_versions_owner_all
  on public.resume_profile_versions
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

grant select, insert, update, delete on public.resume_profile_versions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
