begin;

-- Stage 4: persist target-job resume optimization versions server-side.
create table if not exists public.resume_optimizations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  resume_id integer not null references public.resumes(id) on delete cascade,
  job_id integer references public.jobs(id) on delete set null,
  resume_profile_version integer not null,
  target_company text not null default '',
  target_position text not null,
  target_region text,
  original_content text not null,
  optimized_content jsonb not null default '{}'::jsonb,
  reviewed_content jsonb,
  edited_content text,
  change_items jsonb not null default '[]'::jsonb,
  score_comparison jsonb,
  original_score integer,
  optimized_score integer,
  is_english boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint resume_optimizations_profile_version_check check (resume_profile_version > 0),
  constraint resume_optimizations_optimized_content_check check (jsonb_typeof(optimized_content) = 'object')
);

alter table public.resume_optimizations
  add column if not exists edited_content text,
  add column if not exists reviewed_content jsonb,
  add column if not exists change_items jsonb not null default '[]'::jsonb,
  add column if not exists score_comparison jsonb,
  add column if not exists original_score integer,
  add column if not exists optimized_score integer;

alter table public.resume_optimizations
  drop constraint if exists resume_optimizations_original_score_check,
  drop constraint if exists resume_optimizations_optimized_score_check,
  drop constraint if exists resume_optimizations_reviewed_content_check,
  drop constraint if exists resume_optimizations_change_items_array_check;

alter table public.resume_optimizations
  add constraint resume_optimizations_original_score_check
    check (original_score is null or original_score between 0 and 100),
  add constraint resume_optimizations_optimized_score_check
    check (optimized_score is null or optimized_score between 0 and 100),
  add constraint resume_optimizations_reviewed_content_check
    check (reviewed_content is null or jsonb_typeof(reviewed_content) = 'object'),
  add constraint resume_optimizations_change_items_array_check
    check (jsonb_typeof(change_items) = 'array');

create index if not exists resume_optimizations_user_idx
  on public.resume_optimizations(user_id, created_at desc);
create index if not exists resume_optimizations_resume_version_idx
  on public.resume_optimizations(resume_id, resume_profile_version);
create index if not exists resume_optimizations_job_idx
  on public.resume_optimizations(job_id, created_at desc);

alter table public.resume_optimizations enable row level security;

drop policy if exists resume_optimizations_owner_all on public.resume_optimizations;
create policy resume_optimizations_owner_all
  on public.resume_optimizations
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

grant select, insert, update, delete on public.resume_optimizations to authenticated;
grant usage, select on all sequences in schema public to authenticated;

comment on table public.resume_optimizations is
  'User-owned target-job resume optimization snapshots with original content and confirmed profile version';
comment on column public.resume_optimizations.optimized_content is
  'Validated structured resume data returned by the optimization model';
comment on column public.resume_optimizations.reviewed_content is
  'Current structured resume after user review; optimized_content remains the immutable model result';

commit;
