begin;

create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  request_id text not null unique,
  user_id uuid references auth.users(id) on delete set null,
  feature text not null,
  provider text not null,
  model text,
  status text not null default 'success',
  usage_source text not null default 'unknown',
  input_tokens bigint,
  output_tokens bigint,
  total_tokens bigint,
  estimated_cost numeric(18, 8),
  currency text not null default 'USD',
  resume_id integer references public.resumes(id) on delete set null,
  job_id integer references public.jobs(id) on delete set null,
  interview_session_id integer references public.interview_sessions(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  error_code text,
  error_message text,
  duration_ms integer,
  created_at timestamptz not null default now(),
  constraint ai_usage_events_status_check check (status in ('success', 'error')),
  constraint ai_usage_events_source_check check (usage_source in ('actual', 'estimated', 'unknown')),
  constraint ai_usage_events_tokens_check check (
    (input_tokens is null or input_tokens >= 0)
    and (output_tokens is null or output_tokens >= 0)
    and (total_tokens is null or total_tokens >= 0)
  ),
  constraint ai_usage_events_duration_check check (duration_ms is null or duration_ms >= 0)
);

create index if not exists ai_usage_events_user_created_idx
  on public.ai_usage_events(user_id, created_at desc);
create index if not exists ai_usage_events_feature_created_idx
  on public.ai_usage_events(feature, created_at desc);
create index if not exists ai_usage_events_created_idx
  on public.ai_usage_events(created_at desc);
create index if not exists ai_usage_events_session_idx
  on public.ai_usage_events(interview_session_id)
  where interview_session_id is not null;

alter table public.ai_usage_events enable row level security;

drop policy if exists ai_usage_events_owner_select on public.ai_usage_events;
create policy ai_usage_events_owner_select
  on public.ai_usage_events
  for select to authenticated
  using (user_id = auth.uid());

revoke all on table public.ai_usage_events from anon, authenticated;
grant select on table public.ai_usage_events to authenticated;
grant select, insert, update on table public.ai_usage_events to service_role;
grant usage, select on sequence public.ai_usage_events_id_seq to service_role;

create or replace function public.get_ai_usage_summary(
  p_user_id uuid default null,
  p_feature text default null,
  p_provider text default null,
  p_status text default null,
  p_usage_source text default null,
  p_from timestamptz default null,
  p_to timestamptz default null
)
returns table (
  call_count bigint,
  successful_calls bigint,
  failed_calls bigint,
  input_tokens bigint,
  output_tokens bigint,
  total_tokens bigint,
  actual_calls bigint,
  estimated_calls bigint,
  unknown_calls bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    count(*)::bigint,
    count(*) filter (where status = 'success')::bigint,
    count(*) filter (where status = 'error')::bigint,
    coalesce(sum(input_tokens), 0)::bigint,
    coalesce(sum(output_tokens), 0)::bigint,
    coalesce(sum(total_tokens), 0)::bigint,
    count(*) filter (where usage_source = 'actual')::bigint,
    count(*) filter (where usage_source = 'estimated')::bigint,
    count(*) filter (where usage_source = 'unknown')::bigint
  from public.ai_usage_events
  where (p_user_id is null or user_id = p_user_id)
    and (p_feature is null or feature = p_feature)
    and (p_provider is null or provider = p_provider)
    and (p_status is null or status = p_status)
    and (p_usage_source is null or usage_source = p_usage_source)
    and (p_from is null or created_at >= p_from)
    and (p_to is null or created_at < p_to);
$$;

create or replace function public.get_ai_usage_student_summary(
  p_feature text default null,
  p_provider text default null,
  p_status text default null,
  p_usage_source text default null,
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_page integer default 1,
  p_page_size integer default 50
)
returns table (
  user_id uuid,
  call_count bigint,
  successful_calls bigint,
  failed_calls bigint,
  input_tokens bigint,
  output_tokens bigint,
  total_tokens bigint,
  actual_calls bigint,
  estimated_calls bigint,
  unknown_calls bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    events.user_id,
    count(*)::bigint,
    count(*) filter (where events.status = 'success')::bigint,
    count(*) filter (where events.status = 'error')::bigint,
    coalesce(sum(events.input_tokens), 0)::bigint,
    coalesce(sum(events.output_tokens), 0)::bigint,
    coalesce(sum(events.total_tokens), 0)::bigint,
    count(*) filter (where events.usage_source = 'actual')::bigint,
    count(*) filter (where events.usage_source = 'estimated')::bigint,
    count(*) filter (where events.usage_source = 'unknown')::bigint
  from public.ai_usage_events events
  where events.user_id is not null
    and (p_feature is null or events.feature = p_feature)
    and (p_provider is null or events.provider = p_provider)
    and (p_status is null or events.status = p_status)
    and (p_usage_source is null or events.usage_source = p_usage_source)
    and (p_from is null or events.created_at >= p_from)
    and (p_to is null or events.created_at < p_to)
  group by events.user_id
  order by coalesce(sum(events.total_tokens), 0) desc, events.user_id
  offset greatest(p_page - 1, 0) * least(greatest(p_page_size, 1), 100)
  limit least(greatest(p_page_size, 1), 100);
$$;

revoke all on function public.get_ai_usage_summary(uuid, text, text, text, text, timestamptz, timestamptz) from public;
revoke all on function public.get_ai_usage_student_summary(text, text, text, text, timestamptz, timestamptz, integer, integer) from public;
grant execute on function public.get_ai_usage_summary(uuid, text, text, text, text, timestamptz, timestamptz) to service_role;
grant execute on function public.get_ai_usage_student_summary(text, text, text, text, timestamptz, timestamptz, integer, integer) to service_role;

commit;
