begin;

create table if not exists public.personality_assessments (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  resume_id integer references public.resumes(id) on delete set null,
  model text not null default 'career_fit',
  answers jsonb not null default '[]'::jsonb,
  result jsonb not null default '{}'::jsonb,
  recommendations jsonb not null default '[]'::jsonb,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.personality_assessments enable row level security;

drop policy if exists personality_assessments_owner_all on public.personality_assessments;
create policy personality_assessments_owner_all
  on public.personality_assessments
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

grant select, insert, update, delete on public.personality_assessments to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create index if not exists personality_assessments_user_idx
  on public.personality_assessments(user_id, updated_at desc);

comment on table public.personality_assessments is
  'Latest career-fit personality assessment per user with job direction recommendations';

commit;
