begin;

create table if not exists public.ai_model_prices (
  id bigint generated by default as identity primary key,
  provider text not null,
  model text not null,
  currency text not null default 'USD',
  input_token_price_per_million numeric(18, 8),
  output_token_price_per_million numeric(18, 8),
  audio_second_price numeric(18, 8),
  billing_unit_price numeric(18, 8),
  effective_from timestamptz not null default now(),
  effective_to timestamptz,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_model_prices_currency_check check (currency ~ '^[A-Z]{3}$'),
  constraint ai_model_prices_range_check check (effective_to is null or effective_to > effective_from),
  constraint ai_model_prices_values_check check (
    (input_token_price_per_million is null or input_token_price_per_million >= 0)
    and (output_token_price_per_million is null or output_token_price_per_million >= 0)
    and (audio_second_price is null or audio_second_price >= 0)
    and (billing_unit_price is null or billing_unit_price >= 0)
  ),
  constraint ai_model_prices_measurement_check check (
    (input_token_price_per_million is not null or output_token_price_per_million is not null or audio_second_price is not null or billing_unit_price is not null)
    and not (
      (input_token_price_per_million is not null or output_token_price_per_million is not null)
      and (audio_second_price is not null or billing_unit_price is not null)
    )
    and not (audio_second_price is not null and billing_unit_price is not null)
  )
);

create index if not exists ai_model_prices_lookup_idx
  on public.ai_model_prices(provider, model, effective_from desc)
  where is_active = true;

alter table public.ai_model_prices enable row level security;
revoke all on table public.ai_model_prices from anon, authenticated;
grant select, insert, update on table public.ai_model_prices to service_role;
grant usage, select on sequence public.ai_model_prices_id_seq to service_role;

alter table public.ai_usage_events
  add column if not exists price_id bigint references public.ai_model_prices(id) on delete set null,
  add column if not exists price_snapshot jsonb,
  add column if not exists cost_source text not null default 'unpriced';

alter table public.ai_usage_events
  drop constraint if exists ai_usage_events_cost_source_check;
alter table public.ai_usage_events
  add constraint ai_usage_events_cost_source_check
    check (cost_source in ('priced', 'unpriced'));

create index if not exists ai_usage_events_price_created_idx
  on public.ai_usage_events(price_id, created_at desc)
  where price_id is not null;

create or replace function public.get_ai_usage_summary_v3(
  p_user_id uuid default null,
  p_feature text default null,
  p_provider text default null,
  p_status text default null,
  p_usage_source text default null,
  p_from timestamptz default null,
  p_to timestamptz default null
)
returns table (
  call_count bigint,
  successful_calls bigint,
  failed_calls bigint,
  input_tokens bigint,
  output_tokens bigint,
  total_tokens bigint,
  actual_calls bigint,
  estimated_calls bigint,
  unknown_calls bigint,
  audio_calls bigint,
  input_audio_seconds numeric,
  output_audio_seconds numeric,
  input_audio_bytes bigint,
  output_audio_bytes bigint,
  audio_tokens bigint,
  text_characters bigint,
  billing_units numeric,
  priced_calls bigint,
  unpriced_calls bigint,
  estimated_costs jsonb
)
language sql
stable
security definer
set search_path = public
as $$
  with filtered as materialized (
    select *
    from public.ai_usage_events events
    where (p_user_id is null or events.user_id = p_user_id)
      and (p_feature is null or events.feature = p_feature)
      and (p_provider is null or events.provider = p_provider)
      and (p_status is null or events.status = p_status)
      and (p_usage_source is null or events.usage_source = p_usage_source)
      and (p_from is null or events.created_at >= p_from)
      and (p_to is null or events.created_at < p_to)
  ), cost_totals as (
    select currency, sum(estimated_cost)::numeric(18, 8) as amount
    from filtered
    where estimated_cost is not null
    group by currency
  )
  select
    count(*)::bigint,
    count(*) filter (where status = 'success')::bigint,
    count(*) filter (where status = 'error')::bigint,
    coalesce(sum(input_tokens), 0)::bigint,
    coalesce(sum(output_tokens), 0)::bigint,
    coalesce(sum(total_tokens), 0)::bigint,
    count(*) filter (where usage_source = 'actual')::bigint,
    count(*) filter (where usage_source = 'estimated')::bigint,
    count(*) filter (where usage_source = 'unknown')::bigint,
    count(*) filter (where modality = 'audio')::bigint,
    coalesce(sum(input_audio_seconds), 0),
    coalesce(sum(output_audio_seconds), 0),
    coalesce(sum(input_audio_bytes), 0)::bigint,
    coalesce(sum(output_audio_bytes), 0)::bigint,
    coalesce(sum(audio_tokens), 0)::bigint,
    coalesce(sum(text_characters), 0)::bigint,
    coalesce(sum(billing_units), 0),
    count(*) filter (where estimated_cost is not null)::bigint,
    count(*) filter (where estimated_cost is null)::bigint,
    coalesce((select jsonb_object_agg(currency, amount) from cost_totals), '{}'::jsonb)
  from filtered;
$$;

create or replace function public.get_ai_usage_feature_summary_v3(
  p_user_id uuid default null,
  p_feature text default null,
  p_provider text default null,
  p_status text default null,
  p_usage_source text default null,
  p_from timestamptz default null,
  p_to timestamptz default null
)
returns table (
  feature text,
  call_count bigint,
  successful_calls bigint,
  failed_calls bigint,
  input_tokens bigint,
  output_tokens bigint,
  total_tokens bigint,
  actual_calls bigint,
  estimated_calls bigint,
  unknown_calls bigint,
  audio_calls bigint,
  input_audio_seconds numeric,
  output_audio_seconds numeric,
  audio_tokens bigint,
  text_characters bigint,
  billing_units numeric,
  priced_calls bigint,
  unpriced_calls bigint,
  estimated_costs jsonb
)
language sql
stable
security definer
set search_path = public
as $$
  with filtered as materialized (
    select *
    from public.ai_usage_events events
    where (p_user_id is null or events.user_id = p_user_id)
      and (p_feature is null or events.feature = p_feature)
      and (p_provider is null or events.provider = p_provider)
      and (p_status is null or events.status = p_status)
      and (p_usage_source is null or events.usage_source = p_usage_source)
      and (p_from is null or events.created_at >= p_from)
      and (p_to is null or events.created_at < p_to)
  ), cost_totals as (
    select feature, currency, sum(estimated_cost)::numeric(18, 8) as amount
    from filtered
    where estimated_cost is not null
    group by feature, currency
  )
  select
    events.feature,
    count(*)::bigint,
    count(*) filter (where events.status = 'success')::bigint,
    count(*) filter (where events.status = 'error')::bigint,
    coalesce(sum(events.input_tokens), 0)::bigint,
    coalesce(sum(events.output_tokens), 0)::bigint,
    coalesce(sum(events.total_tokens), 0)::bigint,
    count(*) filter (where events.usage_source = 'actual')::bigint,
    count(*) filter (where events.usage_source = 'estimated')::bigint,
    count(*) filter (where events.usage_source = 'unknown')::bigint,
    count(*) filter (where events.modality = 'audio')::bigint,
    coalesce(sum(events.input_audio_seconds), 0),
    coalesce(sum(events.output_audio_seconds), 0),
    coalesce(sum(events.audio_tokens), 0)::bigint,
    coalesce(sum(events.text_characters), 0)::bigint,
    coalesce(sum(events.billing_units), 0),
    count(*) filter (where events.estimated_cost is not null)::bigint,
    count(*) filter (where events.estimated_cost is null)::bigint,
    coalesce((
      select jsonb_object_agg(currency, amount)
      from cost_totals
      where cost_totals.feature = events.feature
    ), '{}'::jsonb)
  from filtered events
  group by events.feature
  order by coalesce(sum(events.estimated_cost), 0) desc, coalesce(sum(events.total_tokens), 0) desc, events.feature;
$$;

create or replace function public.get_ai_usage_student_summary_v4(
  p_feature text default null,
  p_provider text default null,
  p_status text default null,
  p_usage_source text default null,
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_page integer default 1,
  p_page_size integer default 50
)
returns table (
  user_id uuid,
  display_name text,
  call_count bigint,
  successful_calls bigint,
  failed_calls bigint,
  input_tokens bigint,
  output_tokens bigint,
  total_tokens bigint,
  actual_calls bigint,
  estimated_calls bigint,
  unknown_calls bigint,
  audio_calls bigint,
  input_audio_seconds numeric,
  output_audio_seconds numeric,
  audio_tokens bigint,
  text_characters bigint,
  billing_units numeric,
  priced_calls bigint,
  unpriced_calls bigint,
  estimated_costs jsonb
)
language sql
stable
security definer
set search_path = public
as $$
  with filtered as materialized (
    select *
    from public.ai_usage_events events
    where events.user_id is not null
      and (p_feature is null or events.feature = p_feature)
      and (p_provider is null or events.provider = p_provider)
      and (p_status is null or events.status = p_status)
      and (p_usage_source is null or events.usage_source = p_usage_source)
      and (p_from is null or events.created_at >= p_from)
      and (p_to is null or events.created_at < p_to)
  ), cost_totals as (
    select user_id, currency, sum(estimated_cost)::numeric(18, 8) as amount
    from filtered
    where estimated_cost is not null
    group by user_id, currency
  )
  select
    events.user_id,
    coalesce(nullif(profiles.display_name, ''), '未命名用户')::text,
    count(*)::bigint,
    count(*) filter (where events.status = 'success')::bigint,
    count(*) filter (where events.status = 'error')::bigint,
    coalesce(sum(events.input_tokens), 0)::bigint,
    coalesce(sum(events.output_tokens), 0)::bigint,
    coalesce(sum(events.total_tokens), 0)::bigint,
    count(*) filter (where events.usage_source = 'actual')::bigint,
    count(*) filter (where events.usage_source = 'estimated')::bigint,
    count(*) filter (where events.usage_source = 'unknown')::bigint,
    count(*) filter (where events.modality = 'audio')::bigint,
    coalesce(sum(events.input_audio_seconds), 0),
    coalesce(sum(events.output_audio_seconds), 0),
    coalesce(sum(events.audio_tokens), 0)::bigint,
    coalesce(sum(events.text_characters), 0)::bigint,
    coalesce(sum(events.billing_units), 0),
    count(*) filter (where events.estimated_cost is not null)::bigint,
    count(*) filter (where events.estimated_cost is null)::bigint,
    coalesce((
      select jsonb_object_agg(currency, amount)
      from cost_totals
      where cost_totals.user_id = events.user_id
    ), '{}'::jsonb)
  from filtered events
  left join public.profiles profiles on profiles.id = events.user_id
  group by events.user_id, profiles.display_name
  order by coalesce(sum(events.estimated_cost), 0) desc, coalesce(sum(events.total_tokens), 0) desc, events.user_id
  offset greatest(p_page - 1, 0) * least(greatest(p_page_size, 1), 100)
  limit least(greatest(p_page_size, 1), 100);
$$;

revoke all on function public.get_ai_usage_summary_v3(uuid, text, text, text, text, timestamptz, timestamptz) from public;
revoke all on function public.get_ai_usage_feature_summary_v3(uuid, text, text, text, text, timestamptz, timestamptz) from public;
revoke all on function public.get_ai_usage_student_summary_v4(text, text, text, text, timestamptz, timestamptz, integer, integer) from public;
grant execute on function public.get_ai_usage_summary_v3(uuid, text, text, text, text, timestamptz, timestamptz) to service_role;
grant execute on function public.get_ai_usage_feature_summary_v3(uuid, text, text, text, text, timestamptz, timestamptz) to service_role;
grant execute on function public.get_ai_usage_student_summary_v4(text, text, text, text, timestamptz, timestamptz, integer, integer) to service_role;

commit;
