begin;

alter table public.interview_sessions
  add column if not exists language varchar(2) not null default 'zh',
  add column if not exists evaluation_mode varchar(20) not null default 'dual',
  add column if not exists revision bigint not null default 0,
  add column if not exists ended_reason varchar(30),
  add column if not exists completed_at timestamptz,
  add column if not exists last_request_id varchar(80),
  add column if not exists state_version integer not null default 1;

alter table public.interview_sessions
  drop constraint if exists interview_sessions_language_check;
alter table public.interview_sessions
  add constraint interview_sessions_language_check check (language in ('zh', 'en'));
alter table public.interview_sessions
  drop constraint if exists interview_sessions_evaluation_mode_check;
alter table public.interview_sessions
  add constraint interview_sessions_evaluation_mode_check check (evaluation_mode in ('coach', 'committee', 'dual'));
alter table public.interview_sessions
  drop constraint if exists interview_sessions_ended_reason_check;
alter table public.interview_sessions
  add constraint interview_sessions_ended_reason_check check (ended_reason is null or ended_reason in ('manual', 'timeout', 'round_end', 'eliminated', 'wrap_up', 'error'));

create table if not exists public.interview_turns (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id integer not null references public.interview_sessions(id) on delete cascade,
  turn_index integer not null,
  round integer not null default 1,
  role varchar(20) not null,
  content text not null,
  client_request_id varchar(80),
  input_source varchar(20),
  interviewer_id integer,
  provider_request_id varchar(120),
  question_hash varchar(64),
  intent_key varchar(100),
  dimension varchar(120),
  scenario_key varchar(100),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint interview_turns_role_check check (role in ('interviewer', 'candidate')),
  constraint interview_turns_input_source_check check (input_source is null or input_source in ('text', 'asr', 'asr_fallback', 'system')),
  unique (session_id, turn_index),
  unique (session_id, client_request_id, role)
);

create index if not exists interview_turns_session_created_idx on public.interview_turns(session_id, created_at);
create index if not exists interview_turns_user_company_idx on public.interview_turns(user_id, created_at desc);
create index if not exists interview_turns_question_hash_idx on public.interview_turns(user_id, question_hash) where question_hash is not null;

create table if not exists public.interview_questions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id integer not null references public.interview_sessions(id) on delete cascade,
  turn_id bigint references public.interview_turns(id) on delete set null,
  company_name varchar(255) not null,
  job_id integer references public.jobs(id) on delete set null,
  interview_type varchar(100) not null,
  round_role varchar(50),
  interviewer_id integer,
  dimension varchar(120) not null default 'general',
  intent_key varchar(100) not null default 'general',
  scenario_key varchar(100),
  question_text text not null,
  question_hash varchar(64) not null,
  dna_version integer,
  practice_mode varchar(20) not null default 'fresh',
  asked_at timestamptz not null default now(),
  unique (session_id, question_hash)
);

create index if not exists interview_questions_history_idx on public.interview_questions(user_id, company_name, job_id, asked_at desc);
create index if not exists interview_questions_intent_idx on public.interview_questions(user_id, company_name, intent_key, asked_at desc);

create table if not exists public.interview_answer_signals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id integer not null references public.interview_sessions(id) on delete cascade,
  turn_id bigint references public.interview_turns(id) on delete cascade,
  response_latency_ms integer,
  answer_duration_ms integer,
  quality_labels jsonb not null default '[]'::jsonb,
  missing_data jsonb not null default '[]'::jsonb,
  logic_breaks jsonb not null default '[]'::jsonb,
  practice_recommendations jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.interview_realtime_tickets (
  id bigint generated by default as identity primary key,
  ticket_hash varchar(64) not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id integer references public.interview_sessions(id) on delete cascade,
  capability varchar(10) not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  constraint interview_realtime_tickets_capability_check check (capability in ('asr', 'tts'))
);

create index if not exists interview_realtime_tickets_lookup_idx on public.interview_realtime_tickets(ticket_hash, expires_at) where used_at is null;

alter table public.interview_turns enable row level security;
alter table public.interview_questions enable row level security;
alter table public.interview_answer_signals enable row level security;
alter table public.interview_realtime_tickets enable row level security;

drop policy if exists interview_turns_owner_all on public.interview_turns;
create policy interview_turns_owner_all on public.interview_turns for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists interview_questions_owner_all on public.interview_questions;
create policy interview_questions_owner_all on public.interview_questions for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists interview_answer_signals_owner_all on public.interview_answer_signals;
create policy interview_answer_signals_owner_all on public.interview_answer_signals for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists interview_realtime_tickets_owner_all on public.interview_realtime_tickets;
create policy interview_realtime_tickets_owner_all on public.interview_realtime_tickets for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

grant select, insert, update on public.interview_turns, public.interview_questions, public.interview_answer_signals, public.interview_realtime_tickets to authenticated;
grant select, insert, update, delete on public.interview_turns, public.interview_questions, public.interview_answer_signals, public.interview_realtime_tickets to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
