begin;

create table if not exists public.admin_permissions (
  key text primary key,
  description text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_roles (
  key text primary key,
  description text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_role_permissions (
  role_key text not null references public.admin_roles(key) on delete cascade,
  permission_key text not null references public.admin_permissions(key) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (role_key, permission_key)
);

create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  role_key text not null references public.admin_roles(key),
  status text not null default 'active',
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_users_status_check check (status in ('active', 'suspended'))
);

insert into public.admin_roles (key, description) values
  ('super_admin', '系统、安全、权限和全部后台操作'),
  ('content_admin', '企业 DNA、岗位和内容审核'),
  ('support_admin', '用户摘要和面试反馈处理'),
  ('legacy_super_admin', '共享管理员密码的兼容角色，迁移到账号体系前拥有全部权限')
on conflict (key) do update set description = excluded.description;

insert into public.admin_permissions (key, description) values
  ('admin.dashboard.read', '查看管理员仪表盘'),
  ('admin.dna.read', '查看企业 DNA 和版本'),
  ('admin.dna.write', '编辑企业 DNA 草稿'),
  ('admin.dna.publish', '发布或回滚企业 DNA'),
  ('admin.feedback.read', '查看面试反馈'),
  ('admin.feedback.review', '处理面试反馈'),
  ('admin.jobs.read', '查看岗位运营数据'),
  ('admin.jobs.write', '修改岗位数据'),
  ('admin.users.read', '查看用户脱敏摘要'),
  ('admin.config.write', '修改系统配置'),
  ('admin.audit.read', '查看审计日志'),
  ('admin.roles.write', '修改管理员角色')
on conflict (key) do update set description = excluded.description;

insert into public.admin_role_permissions (role_key, permission_key)
select role_key, permission_key
from (values
  ('super_admin', 'admin.dashboard.read'), ('super_admin', 'admin.dna.read'),
  ('super_admin', 'admin.dna.write'), ('super_admin', 'admin.dna.publish'),
  ('super_admin', 'admin.feedback.read'), ('super_admin', 'admin.feedback.review'),
  ('super_admin', 'admin.jobs.read'), ('super_admin', 'admin.jobs.write'),
  ('super_admin', 'admin.users.read'), ('super_admin', 'admin.config.write'),
  ('super_admin', 'admin.audit.read'), ('super_admin', 'admin.roles.write'),
  ('content_admin', 'admin.dashboard.read'), ('content_admin', 'admin.dna.read'),
  ('content_admin', 'admin.dna.write'), ('content_admin', 'admin.dna.publish'),
  ('content_admin', 'admin.feedback.read'), ('content_admin', 'admin.feedback.review'),
  ('content_admin', 'admin.jobs.read'), ('content_admin', 'admin.jobs.write'),
  ('support_admin', 'admin.dashboard.read'), ('support_admin', 'admin.feedback.read'),
  ('support_admin', 'admin.feedback.review'), ('support_admin', 'admin.users.read'),
  ('legacy_super_admin', 'admin.dashboard.read'), ('legacy_super_admin', 'admin.dna.read'),
  ('legacy_super_admin', 'admin.dna.write'), ('legacy_super_admin', 'admin.dna.publish'),
  ('legacy_super_admin', 'admin.feedback.read'), ('legacy_super_admin', 'admin.feedback.review'),
  ('legacy_super_admin', 'admin.jobs.read'), ('legacy_super_admin', 'admin.jobs.write'),
  ('legacy_super_admin', 'admin.users.read'), ('legacy_super_admin', 'admin.config.write'),
  ('legacy_super_admin', 'admin.audit.read'), ('legacy_super_admin', 'admin.roles.write')
) as permissions(role_key, permission_key)
on conflict (role_key, permission_key) do nothing;

create table if not exists public.company_dna_versions (
  id bigint generated by default as identity primary key,
  company_dna_id integer not null references public.company_dna(id) on delete cascade,
  company_name varchar(255) not null,
  version integer not null,
  aliases jsonb not null default '[]'::jsonb,
  dna jsonb not null,
  source varchar(30) not null default 'manual',
  review_notes text,
  published_by text,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (company_dna_id, version)
);

create index if not exists company_dna_versions_company_idx
  on public.company_dna_versions(company_dna_id, version desc);

insert into public.company_dna_versions (
  company_dna_id, company_name, version, aliases, dna, source, review_notes, published_at
)
select id, company_name, version, aliases, dna, coalesce(source, 'generated'), review_notes, coalesce(updated_at, created_at)
from public.company_dna
on conflict (company_dna_id, version) do nothing;

alter table public.admin_permissions enable row level security;
alter table public.admin_roles enable row level security;
alter table public.admin_role_permissions enable row level security;
alter table public.admin_users enable row level security;
alter table public.company_dna_versions enable row level security;

revoke all on table public.admin_permissions, public.admin_roles, public.admin_role_permissions, public.admin_users, public.company_dna_versions from anon, authenticated;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on sequence public.company_dna_versions_id_seq to service_role;

create or replace function public.publish_company_dna(
  p_company_dna_id integer,
  p_company_name varchar(255),
  p_aliases jsonb,
  p_dna jsonb,
  p_review_notes text,
  p_published_by text
)
returns table (id integer, version integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  next_id integer;
  next_version integer;
begin
  if p_company_dna_id is null then
    insert into public.company_dna (company_name, aliases, dna, source, manually_edited, review_notes, version, updated_at)
    values (p_company_name, coalesce(p_aliases, '[]'::jsonb), p_dna, 'manual', true, p_review_notes, 1, now())
    returning company_dna.id, company_dna.version into next_id, next_version;
  else
    update public.company_dna
    set aliases = coalesce(p_aliases, aliases), dna = p_dna, source = 'manual', manually_edited = true,
        review_notes = p_review_notes, version = version + 1, updated_at = now()
    where company_dna.id = p_company_dna_id
    returning company_dna.id, company_dna.version into next_id, next_version;
    if next_id is null then raise exception 'company_dna_not_found'; end if;
  end if;

  insert into public.company_dna_versions (
    company_dna_id, company_name, version, aliases, dna, source, review_notes, published_by
  )
  select id, company_name, version, aliases, dna, source, review_notes, p_published_by
  from public.company_dna where id = next_id;

  return query select next_id, next_version;
end;
$$;

create or replace function public.rollback_company_dna_version(
  p_version_id bigint,
  p_published_by text,
  p_review_notes text default null
)
returns table (id integer, version integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  snapshot public.company_dna_versions%rowtype;
  next_version integer;
begin
  select * into snapshot from public.company_dna_versions where company_dna_versions.id = p_version_id;
  if snapshot.id is null then raise exception 'company_dna_version_not_found'; end if;

  update public.company_dna
  set aliases = snapshot.aliases, dna = snapshot.dna, source = 'manual', manually_edited = true,
      review_notes = coalesce(p_review_notes, '回滚至历史版本 v' || snapshot.version),
      version = version + 1, updated_at = now()
  where company_dna.id = snapshot.company_dna_id
  returning company_dna.version into next_version;

  insert into public.company_dna_versions (
    company_dna_id, company_name, version, aliases, dna, source, review_notes, published_by
  ) values (
    snapshot.company_dna_id, snapshot.company_name, next_version, snapshot.aliases, snapshot.dna,
    'manual', coalesce(p_review_notes, '回滚至历史版本 v' || snapshot.version), p_published_by
  );

  return query select snapshot.company_dna_id, next_version;
end;
$$;

revoke all on function public.publish_company_dna(integer, varchar, jsonb, jsonb, text, text) from public;
revoke all on function public.rollback_company_dna_version(bigint, text, text) from public;
grant execute on function public.publish_company_dna(integer, varchar, jsonb, jsonb, text, text) to service_role;
grant execute on function public.rollback_company_dna_version(bigint, text, text) to service_role;

commit;
