begin;

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  price_monthly numeric(10, 2) not null default 0,
  price_yearly numeric(10, 2) not null default 0,
  currency text not null default 'USD',
  entitlements jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  plan_id bigint not null references public.plans(id) on delete restrict,
  stripe_customer_id text,
  stripe_subscription_id text,
  status text not null default 'active',
  billing_interval text not null default 'monthly',
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint subscriptions_status_check check (status in ('active', 'trialing', 'past_due', 'canceled')),
  constraint subscriptions_interval_check check (billing_interval in ('monthly', 'yearly'))
);

create table if not exists public.entitlements (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.plans(id) on delete cascade,
  feature_code text not null,
  quota_per_month integer,
  grant_on_signup integer not null default 0,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint entitlements_plan_feature_unique unique (plan_id, feature_code),
  constraint entitlements_feature_check check (
    feature_code in (
      'ai_match',
      'ats_optimize',
      'mock_interview',
      'networking',
      'dashboard_advanced',
      'auto_apply'
    )
  ),
  constraint entitlements_quota_check check (
    quota_per_month is null or quota_per_month >= 0
  )
);

create table if not exists public.usage_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  feature_code text not null,
  bucket_key text not null,
  source text not null default 'monthly',
  used_count integer not null default 0,
  limit_value integer,
  period_start timestamptz,
  period_end timestamptz,
  credit_pack_id bigint,
  ai_usage_event_id bigint references public.ai_usage_events(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint usage_ledger_user_feature_bucket_unique unique (user_id, feature_code, bucket_key),
  constraint usage_ledger_source_check check (source in ('monthly', 'grant', 'credit_pack')),
  constraint usage_ledger_count_check check (used_count >= 0),
  constraint usage_ledger_limit_check check (limit_value is null or limit_value >= 0)
);

create table if not exists public.credit_packs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  feature_code text not null,
  stripe_payment_intent_id text,
  quantity integer not null default 0,
  remaining integer not null default 0,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint credit_packs_feature_check check (
    feature_code in (
      'ai_match',
      'ats_optimize',
      'mock_interview',
      'networking',
      'dashboard_advanced',
      'auto_apply'
    )
  ),
  constraint credit_packs_count_check check (
    quantity >= 0 and remaining >= 0 and remaining <= quantity
  ),
  constraint credit_packs_status_check check (status in ('active', 'consumed', 'refunded'))
);

alter table public.plans enable row level security;
alter table public.subscriptions enable row level security;
alter table public.entitlements enable row level security;
alter table public.usage_ledger enable row level security;
alter table public.credit_packs enable row level security;

drop policy if exists plans_public_select on public.plans;
create policy plans_public_select
  on public.plans
  for select to anon, authenticated
  using (true);

drop policy if exists subscriptions_owner_select on public.subscriptions;
create policy subscriptions_owner_select
  on public.subscriptions
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists entitlements_public_select on public.entitlements;
create policy entitlements_public_select
  on public.entitlements
  for select to anon, authenticated
  using (true);

drop policy if exists usage_ledger_owner_select on public.usage_ledger;
create policy usage_ledger_owner_select
  on public.usage_ledger
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists credit_packs_owner_select on public.credit_packs;
create policy credit_packs_owner_select
  on public.credit_packs
  for select to authenticated
  using (user_id = auth.uid());

revoke all on table public.plans from anon, authenticated;
grant select on table public.plans to anon, authenticated;
revoke all on table public.subscriptions from anon, authenticated;
grant select on table public.subscriptions to authenticated;
revoke all on table public.entitlements from anon, authenticated;
grant select on table public.entitlements to anon, authenticated;
revoke all on table public.usage_ledger from anon, authenticated;
grant select on table public.usage_ledger to authenticated;
revoke all on table public.credit_packs from anon, authenticated;
grant select on table public.credit_packs to authenticated;

grant usage, select on all sequences in schema public to anon, authenticated, service_role;

create index if not exists subscriptions_user_active_idx
  on public.subscriptions(user_id, status)
  where status in ('active', 'trialing');
create index if not exists entitlements_plan_active_idx
  on public.entitlements(plan_id, feature_code, is_active);
create index if not exists usage_ledger_user_bucket_idx
  on public.usage_ledger(user_id, feature_code, bucket_key);
create index if not exists credit_packs_user_active_idx
  on public.credit_packs(user_id, feature_code, status)
  where status = 'active';

insert into public.plans (code, name, price_monthly, price_yearly, currency, entitlements, sort_order)
values
  ('basic', 'Basic', 0, 0, 'USD', '{}'::jsonb, 1),
  ('pro', 'Pro', 29, 228, 'USD', '{}'::jsonb, 2)
on conflict (code) do update set
  name = excluded.name,
  price_monthly = excluded.price_monthly,
  price_yearly = excluded.price_yearly,
  currency = excluded.currency,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();

insert into public.entitlements (plan_id, feature_code, quota_per_month, grant_on_signup, sort_order)
select p.id, e.feature_code, e.quota_per_month, e.grant_on_signup, e.sort_order
from public.plans p
join (
  values
    ('basic', 'ai_match', 3, 3, 1),
    ('basic', 'ats_optimize', 3, 3, 2),
    ('basic', 'mock_interview', 0, 3, 3),
    ('basic', 'networking', 0, 0, 4),
    ('basic', 'dashboard_advanced', 0, 0, 5),
    ('basic', 'auto_apply', 0, 0, 6),
    ('pro', 'ai_match', null, 0, 1),
    ('pro', 'ats_optimize', null, 0, 2),
    ('pro', 'mock_interview', null, 0, 3),
    ('pro', 'networking', null, 0, 4),
    ('pro', 'dashboard_advanced', null, 0, 5),
    ('pro', 'auto_apply', null, 0, 6)
) as e(plan_code, feature_code, quota_per_month, grant_on_signup, sort_order)
  on e.plan_code = p.code
on conflict (plan_id, feature_code) do update set
  quota_per_month = excluded.quota_per_month,
  grant_on_signup = excluded.grant_on_signup,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();

create or replace function public.get_user_entitlements(p_user uuid)
returns table (
  plan_code text,
  plan_name text,
  feature_code text,
  quota_used bigint,
  quota_limit integer,
  grant_used bigint,
  grant_limit integer
)
language sql
stable
security definer
set search_path = public
as $$
  with selected_plan as (
    select p.*
    from public.plans p
    where p.is_active
      and (
        p.code = 'basic'
        or exists (
          select 1
          from public.subscriptions s
          where s.user_id = p_user
            and s.plan_id = p.id
            and s.status in ('active', 'trialing')
            and (s.current_period_end is null or s.current_period_end > now())
        )
      )
    order by case when p.code = 'basic' then 1 else 0 end, p.sort_order
    limit 1
  )
  select
    sp.code,
    sp.name,
    e.feature_code,
    coalesce(m.used_count, 0)::bigint,
    m.limit_value,
    coalesce(g.used_count, 0)::bigint,
    g.limit_value
  from selected_plan sp
  join public.entitlements e on e.plan_id = sp.id and e.is_active
  left join public.usage_ledger m
    on m.user_id = p_user
   and m.feature_code = e.feature_code
   and m.bucket_key = to_char(now(), 'YYYY-MM')
  left join public.usage_ledger g
    on g.user_id = p_user
   and g.feature_code = e.feature_code
   and g.bucket_key = 'signup'
  order by e.sort_order;
$$;

create or replace function public.grant_signup_credits(p_user uuid)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.usage_ledger (
    user_id,
    feature_code,
    bucket_key,
    source,
    used_count,
    limit_value
  )
  select
    p_user,
    e.feature_code,
    'signup',
    'grant',
    0,
    e.grant_on_signup
  from public.entitlements e
  join public.plans p on p.id = e.plan_id
  where p.code = 'basic'
    and e.grant_on_signup > 0
  on conflict (user_id, feature_code, bucket_key) do nothing;
$$;

create or replace function public.consume_feature_usage(
  p_user uuid,
  p_feature text,
  p_quantity integer default 1
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan_id bigint;
  v_plan_code text;
  v_quota integer;
  v_grant integer;
  v_used integer;
  v_limit integer;
  v_bucket text := to_char(now(), 'YYYY-MM');
begin
  if p_user is null or p_feature is null or p_quantity is null or p_quantity < 1 then
    return jsonb_build_object('allowed', false, 'reason', 'INVALID_REQUEST');
  end if;

  select p.id, p.code into v_plan_id, v_plan_code
  from public.plans p
  where p.is_active
    and (
      p.code = 'basic'
      or exists (
        select 1
        from public.subscriptions s
        where s.user_id = p_user
          and s.plan_id = p.id
          and s.status in ('active', 'trialing')
          and (s.current_period_end is null or s.current_period_end > now())
      )
    )
  order by case when p.code = 'basic' then 1 else 0 end, p.sort_order
  limit 1;
  if not found then
    return jsonb_build_object('allowed', false, 'reason', 'PLAN_REQUIRED');
  end if;

  select e.quota_per_month, e.grant_on_signup into v_quota, v_grant
  from public.entitlements e
  where e.plan_id = v_plan_id
    and e.feature_code = p_feature
    and e.is_active;
  if not found then
    return jsonb_build_object('allowed', false, 'reason', 'PLAN_REQUIRED', 'plan', v_plan_code);
  end if;

  if v_quota is null then
    return jsonb_build_object(
      'allowed', true,
      'reason', 'OK',
      'plan', v_plan_code,
      'unlimited', true
    );
  end if;

  insert into public.usage_ledger (
    user_id,
    feature_code,
    bucket_key,
    source,
    used_count,
    limit_value,
    period_start,
    period_end
  )
  values (
    p_user,
    p_feature,
    v_bucket,
    'monthly',
    p_quantity,
    v_quota,
    date_trunc('month', now()),
    date_trunc('month', now()) + interval '1 month'
  )
  on conflict (user_id, feature_code, bucket_key)
  do update set
    used_count = public.usage_ledger.used_count + excluded.used_count,
    updated_at = now()
  where public.usage_ledger.used_count + excluded.used_count <= public.usage_ledger.limit_value
  returning used_count, limit_value into v_used, v_limit;

  if found then
    return jsonb_build_object(
      'allowed', true,
      'reason', 'OK',
      'plan', v_plan_code,
      'used', v_used,
      'limit', v_limit,
      'remaining', v_limit - v_used
    );
  end if;

  select used_count, limit_value into v_used, v_limit
  from public.usage_ledger
  where user_id = p_user
    and feature_code = p_feature
    and bucket_key = v_bucket
  limit 1;
  if found then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'USAGE_EXHAUSTED',
      'plan', v_plan_code,
      'used', v_used,
      'limit', v_limit,
      'remaining', 0
    );
  end if;

  if v_grant is null or v_grant <= 0 then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'PLAN_REQUIRED',
      'plan', v_plan_code
    );
  end if;

  insert into public.usage_ledger (
    user_id,
    feature_code,
    bucket_key,
    source,
    used_count,
    limit_value
  )
  values (
    p_user,
    p_feature,
    'signup',
    'grant',
    p_quantity,
    v_grant
  )
  on conflict (user_id, feature_code, bucket_key)
  do update set
    used_count = public.usage_ledger.used_count + excluded.used_count,
    updated_at = now()
  where public.usage_ledger.used_count + excluded.used_count <= public.usage_ledger.limit_value
  returning used_count, limit_value into v_used, v_limit;

  if found then
    return jsonb_build_object(
      'allowed', true,
      'reason', 'OK',
      'plan', v_plan_code,
      'source', 'grant',
      'used', v_used,
      'limit', v_limit,
      'remaining', v_limit - v_used
    );
  end if;

  return jsonb_build_object(
    'allowed', false,
    'reason', 'USAGE_EXHAUSTED',
    'plan', v_plan_code,
    'remaining', 0
  );
end;
$$;

grant execute on function public.get_user_entitlements(uuid) to authenticated, service_role;
grant execute on function public.grant_signup_credits(uuid) to authenticated, service_role;
grant execute on function public.consume_feature_usage(uuid, text, integer) to authenticated, service_role;

comment on table public.plans is 'Paid plans and prices';
comment on table public.subscriptions is 'User subscriptions, including Stripe metadata when payments are enabled';
comment on table public.entitlements is 'Feature rights and quotas per plan';
comment on table public.usage_ledger is 'Monthly quota and signup-grant consumption ledger';
comment on table public.credit_packs is 'Purchased add-on credit packs';

commit;
