begin;

create table if not exists public.beta_entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  plan_code text not null default 'beta',
  status text not null default 'active',
  period_start timestamptz not null,
  period_end timestamptz not null,
  bonus_limits jsonb not null default '{}'::jsonb,
  source text not null default 'manual_beta',
  version integer not null default 1,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint beta_entitlements_status_check check (status in ('active', 'suspended', 'expired')),
  constraint beta_entitlements_period_check check (period_end > period_start)
);

create table if not exists public.beta_entitlement_limits (
  id bigint generated by default as identity primary key,
  plan_code text not null,
  metric text not null,
  limit_value numeric(18, 4) not null,
  overage_policy text not null default 'deny',
  active_from timestamptz not null default now(),
  active_to timestamptz,
  created_at timestamptz not null default now(),
  constraint beta_limits_value_check check (limit_value >= 0),
  constraint beta_limits_policy_check check (overage_policy in ('deny', 'degrade', 'allow')),
  constraint beta_limits_period_check check (active_to is null or active_to > active_from),
  unique (plan_code, metric, active_from)
);

create table if not exists public.beta_usage_reservations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entitlement_id bigint not null references public.beta_entitlements(id) on delete cascade,
  metric text not null,
  amount numeric(18, 4) not null,
  idempotency_key text not null,
  status text not null default 'reserved',
  expires_at timestamptz not null default (now() + interval '10 minutes'),
  created_at timestamptz not null default now(),
  settled_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint beta_reservation_amount_check check (amount > 0),
  constraint beta_reservation_status_check check (status in ('reserved', 'committed', 'released', 'expired')),
  unique (user_id, idempotency_key)
);

create index if not exists beta_entitlements_status_idx
  on public.beta_entitlements(status, period_end);
create index if not exists beta_usage_reservations_user_metric_idx
  on public.beta_usage_reservations(user_id, metric, created_at desc);
create index if not exists beta_usage_reservations_expiry_idx
  on public.beta_usage_reservations(status, expires_at)
  where status = 'reserved';

create table if not exists public.billing_customers (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  provider text not null,
  provider_customer_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_customer_id)
);

create table if not exists public.billing_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_code text not null,
  provider text not null,
  provider_order_id text,
  status text not null default 'pending',
  amount numeric(18, 2) not null default 0,
  currency text not null default 'USD',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint billing_orders_status_check check (status in ('pending', 'paid', 'cancelled', 'refunded', 'failed')),
  constraint billing_orders_amount_check check (amount >= 0),
  unique (provider, provider_order_id)
);

create table if not exists public.billing_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_id text not null,
  event_type text,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'received',
  result jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  constraint billing_webhook_status_check check (status in ('received', 'processed', 'ignored', 'failed')),
  unique (provider, event_id)
);

insert into public.beta_entitlement_limits (plan_code, metric, limit_value, overage_policy)
values
  ('beta', 'resume_parse', 3, 'deny'),
  ('beta', 'ai_match', 10, 'deny'),
  ('beta', 'resume_optimize', 5, 'deny'),
  ('beta', 'resume_score', 10, 'deny'),
  ('beta', 'interview_turn', 30, 'deny'),
  ('beta', 'ai_text', 30, 'deny'),
  ('beta', 'asr_minutes', 30, 'degrade'),
  ('beta', 'tts_minutes', 30, 'degrade')
on conflict (plan_code, metric, active_from) do nothing;

alter table public.beta_entitlements enable row level security;
alter table public.beta_entitlement_limits enable row level security;
alter table public.beta_usage_reservations enable row level security;
alter table public.billing_customers enable row level security;
alter table public.billing_orders enable row level security;
alter table public.billing_webhook_events enable row level security;

drop policy if exists beta_entitlements_owner_select on public.beta_entitlements;
create policy beta_entitlements_owner_select on public.beta_entitlements
  for select to authenticated using (user_id = auth.uid());
drop policy if exists beta_usage_reservations_owner_select on public.beta_usage_reservations;
create policy beta_usage_reservations_owner_select on public.beta_usage_reservations
  for select to authenticated using (user_id = auth.uid());
drop policy if exists billing_orders_owner_select on public.billing_orders;
create policy billing_orders_owner_select on public.billing_orders
  for select to authenticated using (user_id = auth.uid());

revoke all on public.beta_entitlement_limits from anon, authenticated;
revoke all on public.billing_customers from anon, authenticated;
revoke all on public.billing_webhook_events from anon, authenticated;
grant select on public.beta_entitlements, public.beta_usage_reservations, public.billing_orders to authenticated;
grant select, insert, update, delete on public.beta_entitlements, public.beta_entitlement_limits, public.beta_usage_reservations, public.billing_customers, public.billing_orders, public.billing_webhook_events to service_role;
grant usage, select on sequence public.beta_entitlements_id_seq, public.beta_entitlement_limits_id_seq, public.beta_usage_reservations_id_seq, public.billing_customers_id_seq, public.billing_orders_id_seq, public.billing_webhook_events_id_seq to service_role;

create or replace function public.reserve_beta_usage(
  p_user_id uuid,
  p_metric text,
  p_amount numeric default 1,
  p_idempotency_key text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  allowed boolean,
  code text,
  reservation_id bigint,
  remaining numeric,
  reset_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  entitlement public.beta_entitlements%rowtype;
  limit_value numeric;
  consumed numeric;
  reservation public.beta_usage_reservations%rowtype;
  key_value text := nullif(trim(coalesce(p_idempotency_key, '')), '');
begin
  if p_amount is null or p_amount <= 0 or p_metric is null or trim(p_metric) = '' then
    return query select false, 'INVALID_USAGE_REQUEST', null::bigint, 0::numeric, null::timestamptz;
    return;
  end if;

  if key_value is not null then
    select * into reservation
    from public.beta_usage_reservations r
    where r.user_id = p_user_id and r.idempotency_key = key_value;
    if reservation.id is not null then
      if reservation.status in ('reserved', 'committed') then
        select
          l.limit_value + case
            when coalesce(e.bonus_limits ->> reservation.metric, '') ~ '^-?[0-9]+([.][0-9]+)?$'
              then (e.bonus_limits ->> reservation.metric)::numeric
            else 0
          end,
          e.period_end
        into limit_value, reset_at
        from public.beta_entitlements e
        join public.beta_entitlement_limits l on l.plan_code = e.plan_code
        where e.id = reservation.entitlement_id
          and l.metric = reservation.metric
          and l.active_from <= now()
          and (l.active_to is null or l.active_to > now())
        order by l.active_from desc
        limit 1;
        select coalesce(sum(r.amount), 0) into consumed
        from public.beta_usage_reservations r
        where r.entitlement_id = reservation.entitlement_id
          and r.metric = reservation.metric
          and r.created_at >= (select period_start from public.beta_entitlements where id = reservation.entitlement_id)
          and r.status in ('reserved', 'committed');
        return query select true, 'IDEMPOTENT_REPLAY', reservation.id, greatest(coalesce(limit_value, 0) - consumed, 0), reset_at;
        return;
      end if;
    end if;
  end if;

  select * into entitlement
  from public.beta_entitlements e
  where e.user_id = p_user_id
  for update;
  if entitlement.id is null then
    return query select false, 'BETA_ACCESS_REQUIRED', null::bigint, 0::numeric, null::timestamptz;
    return;
  end if;
  if entitlement.status <> 'active' or now() < entitlement.period_start or now() >= entitlement.period_end then
    return query select false, 'BETA_ACCESS_INACTIVE', null::bigint, 0::numeric, entitlement.period_end;
    return;
  end if;

  select l.limit_value + case
    when coalesce(entitlement.bonus_limits ->> trim(p_metric), '') ~ '^-?[0-9]+([.][0-9]+)?$'
      then (entitlement.bonus_limits ->> trim(p_metric))::numeric
    else 0
  end into limit_value
  from public.beta_entitlement_limits l
  where l.plan_code = entitlement.plan_code
    and l.metric = trim(p_metric)
    and l.active_from <= now()
    and (l.active_to is null or l.active_to > now())
  order by l.active_from desc
  limit 1;
  if limit_value is null then
    return query select false, 'BETA_METRIC_NOT_CONFIGURED', null::bigint, 0::numeric, entitlement.period_end;
    return;
  end if;

  update public.beta_usage_reservations
  set status = 'expired', settled_at = now()
  where user_id = p_user_id and status = 'reserved' and expires_at <= now();

  select coalesce(sum(r.amount), 0) into consumed
  from public.beta_usage_reservations r
  where r.entitlement_id = entitlement.id
    and r.metric = trim(p_metric)
    and r.created_at >= entitlement.period_start
    and r.status in ('reserved', 'committed');

  if consumed + p_amount > limit_value then
    return query select false, 'BETA_QUOTA_EXCEEDED', null::bigint, greatest(limit_value - consumed, 0), entitlement.period_end;
    return;
  end if;

  insert into public.beta_usage_reservations (user_id, entitlement_id, metric, amount, idempotency_key, metadata)
  values (p_user_id, entitlement.id, trim(p_metric), p_amount, coalesce(key_value, md5(random()::text || clock_timestamp()::text || p_user_id::text)), coalesce(p_metadata, '{}'::jsonb))
  returning * into reservation;

  return query select true, 'RESERVED', reservation.id, greatest(limit_value - consumed - p_amount, 0), entitlement.period_end;
exception when unique_violation then
  select * into reservation from public.beta_usage_reservations r where r.user_id = p_user_id and r.idempotency_key = key_value;
  return query select true, 'IDEMPOTENT_REPLAY', reservation.id, 0::numeric, null::timestamptz;
end;
$$;

create or replace function public.settle_beta_usage(
  p_reservation_id bigint,
  p_status text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_status not in ('committed', 'released') then return false; end if;
  update public.beta_usage_reservations
  set status = p_status, settled_at = now()
  where id = p_reservation_id and status = 'reserved';
  return found;
end;
$$;

revoke all on function public.reserve_beta_usage(uuid, text, numeric, text, jsonb) from public;
revoke all on function public.settle_beta_usage(bigint, text) from public;
grant execute on function public.reserve_beta_usage(uuid, text, numeric, text, jsonb) to service_role;
grant execute on function public.settle_beta_usage(bigint, text) to service_role;

commit;
