begin;

create table if not exists public.credit_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  balance numeric(18, 4) not null default 0,
  lifetime_granted numeric(18, 4) not null default 0,
  lifetime_spent numeric(18, 4) not null default 0,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint credit_accounts_balance_check check (balance >= 0),
  constraint credit_accounts_granted_check check (lifetime_granted >= 0),
  constraint credit_accounts_spent_check check (lifetime_spent >= 0)
);

create table if not exists public.credit_price_rules (
  id bigint generated by default as identity primary key,
  metric text not null unique,
  display_name text not null,
  unit_name text not null default '次',
  credit_cost numeric(18, 4) not null,
  enabled boolean not null default true,
  max_units_per_request numeric(18, 4),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint credit_price_rules_cost_check check (credit_cost > 0),
  constraint credit_price_rules_max_check check (max_units_per_request is null or max_units_per_request > 0)
);

create table if not exists public.credit_reservations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  account_id bigint not null references public.credit_accounts(id) on delete cascade,
  metric text not null references public.credit_price_rules(metric),
  units numeric(18, 4) not null,
  credits numeric(18, 4) not null,
  idempotency_key text not null,
  status text not null default 'reserved',
  expires_at timestamptz not null default (now() + interval '10 minutes'),
  created_at timestamptz not null default now(),
  settled_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint credit_reservations_units_check check (units > 0),
  constraint credit_reservations_credits_check check (credits > 0),
  constraint credit_reservations_status_check check (status in ('reserved', 'committed', 'released', 'expired')),
  unique (user_id, idempotency_key)
);

create table if not exists public.credit_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  account_id bigint not null references public.credit_accounts(id) on delete cascade,
  reservation_id bigint references public.credit_reservations(id) on delete set null,
  entry_type text not null,
  delta numeric(18, 4) not null,
  balance_after numeric(18, 4) not null,
  metric text,
  idempotency_key text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint credit_ledger_entry_type_check check (entry_type in ('grant', 'purchase', 'reserve', 'refund', 'adjustment')),
  constraint credit_ledger_balance_check check (balance_after >= 0),
  unique (user_id, idempotency_key)
);

create index if not exists credit_reservations_user_status_idx
  on public.credit_reservations(user_id, status, created_at desc);
create index if not exists credit_reservations_expiry_idx
  on public.credit_reservations(status, expires_at)
  where status = 'reserved';
create index if not exists credit_ledger_user_created_idx
  on public.credit_ledger(user_id, created_at desc);

insert into public.credit_price_rules (metric, display_name, unit_name, credit_cost, max_units_per_request, notes)
values
  ('resume_parse', '简历解析与画像', '份', 20, 1, '上传一份简历并生成画像'),
  ('ai_match', 'AI 选岗', '次', 8, 1, '按一次完整匹配请求计费'),
  ('resume_optimize', '简历优化', '次', 15, 1, '按一次完整优化请求计费'),
  ('resume_score', '简历评分', '次', 5, 1, '按一次评分请求计费'),
  ('interview_turn', 'AI 模拟面试回合', '回合', 12, 1, '高成本能力，按每个 AI 回合计费'),
  ('asr_minutes', '面试语音识别', '分钟', 4, 5, '按实际或估算语音分钟数计费'),
  ('tts_minutes', '面试语音合成', '分钟', 4, 5, '按实际或估算语音分钟数计费'),
  ('application_profile', '求职档案生成', '次', 20, 1, '根据简历生成完整网申档案'),
  ('application_prefill', '网申智能预填', '次', 8, 1, '按一次未解析字段的 AI 预填请求计费'),
  ('career_plan_refine', '求职规划细化', '次', 3, 1, '简历处理中的辅助生成')
on conflict (metric) do nothing;

alter table public.credit_accounts enable row level security;
alter table public.credit_price_rules enable row level security;
alter table public.credit_reservations enable row level security;
alter table public.credit_ledger enable row level security;

drop policy if exists credit_accounts_owner_select on public.credit_accounts;
create policy credit_accounts_owner_select on public.credit_accounts
  for select to authenticated using (user_id = auth.uid());
drop policy if exists credit_price_rules_authenticated_select on public.credit_price_rules;
create policy credit_price_rules_authenticated_select on public.credit_price_rules
  for select to authenticated using (enabled = true);
drop policy if exists credit_reservations_owner_select on public.credit_reservations;
create policy credit_reservations_owner_select on public.credit_reservations
  for select to authenticated using (user_id = auth.uid());
drop policy if exists credit_ledger_owner_select on public.credit_ledger;
create policy credit_ledger_owner_select on public.credit_ledger
  for select to authenticated using (user_id = auth.uid());

revoke all on public.credit_accounts, public.credit_price_rules, public.credit_reservations, public.credit_ledger from anon, authenticated;
grant select on public.credit_accounts, public.credit_price_rules, public.credit_reservations, public.credit_ledger to authenticated;
grant select, insert, update, delete on public.credit_accounts, public.credit_price_rules, public.credit_reservations, public.credit_ledger to service_role;
grant usage, select on sequence public.credit_accounts_id_seq, public.credit_price_rules_id_seq, public.credit_reservations_id_seq, public.credit_ledger_id_seq to service_role;

create or replace function public.reserve_credits(
  p_user_id uuid,
  p_metric text,
  p_units numeric default 1,
  p_idempotency_key text default null,
  p_require_beta boolean default false,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  allowed boolean,
  code text,
  reservation_id bigint,
  credits numeric,
  remaining numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  account public.credit_accounts%rowtype;
  rule public.credit_price_rules%rowtype;
  reservation public.credit_reservations%rowtype;
  key_value text := nullif(trim(coalesce(p_idempotency_key, '')), '');
  charge numeric;
begin
  if p_user_id is null or p_units is null or p_units <= 0 or trim(coalesce(p_metric, '')) = '' then
    return query select false, 'INVALID_CREDIT_REQUEST', null::bigint, 0::numeric, 0::numeric;
    return;
  end if;

  if key_value is not null then
    select * into reservation
      from public.credit_reservations
     where user_id = p_user_id and idempotency_key = key_value;
    if reservation.id is not null and reservation.status in ('reserved', 'committed') then
      select * into account from public.credit_accounts where id = reservation.account_id;
      return query select true, 'IDEMPOTENT_REPLAY', reservation.id, reservation.credits, coalesce(account.balance, 0);
      return;
    end if;
    if reservation.id is not null then
      return query select false, 'IDEMPOTENCY_REPLAY', reservation.id, reservation.credits, 0::numeric;
      return;
    end if;
  end if;

  if p_require_beta then
    if not exists (
      select 1 from public.beta_entitlements e
       where e.user_id = p_user_id
         and e.status = 'active'
         and now() >= e.period_start
         and now() < e.period_end
    ) then
      if exists (select 1 from public.beta_entitlements where user_id = p_user_id) then
        return query select false, 'BETA_ACCESS_INACTIVE', null::bigint, 0::numeric, 0::numeric;
      end if;
      return query select false, 'BETA_ACCESS_REQUIRED', null::bigint, 0::numeric, 0::numeric;
      return;
    end if;
  end if;

  select * into rule from public.credit_price_rules
   where metric = trim(p_metric) and enabled = true;
  if rule.id is null then
    return query select false, 'CREDIT_METRIC_NOT_CONFIGURED', null::bigint, 0::numeric, 0::numeric;
    return;
  end if;
  if rule.max_units_per_request is not null and p_units > rule.max_units_per_request then
    return query select false, 'CREDIT_REQUEST_TOO_LARGE', null::bigint, 0::numeric, 0::numeric;
    return;
  end if;
  charge := rule.credit_cost * p_units;

  insert into public.credit_accounts (user_id) values (p_user_id)
    on conflict (user_id) do nothing;
  select * into account from public.credit_accounts where user_id = p_user_id for update;

  for reservation in
    select * from public.credit_reservations
     where user_id = p_user_id and status = 'reserved' and expires_at <= now()
     for update
  loop
    update public.credit_accounts
       set balance = balance + reservation.credits,
           lifetime_spent = greatest(0, lifetime_spent - reservation.credits),
           version = version + 1,
           updated_at = now()
     where id = reservation.account_id;
    insert into public.credit_ledger (user_id, account_id, reservation_id, entry_type, delta, balance_after, metric, idempotency_key, reason, metadata)
    select reservation.user_id, a.id, reservation.id, 'refund', reservation.credits, a.balance, reservation.metric,
           'refund:' || reservation.id::text, '过期预扣自动退回积分', reservation.metadata
      from public.credit_accounts a where a.id = reservation.account_id;
    update public.credit_reservations set status = 'expired', settled_at = now() where id = reservation.id;
  end loop;
  select * into account from public.credit_accounts where id = account.id for update;

  if account.balance < charge then
    return query select false, 'CREDIT_INSUFFICIENT', null::bigint, charge, account.balance;
    return;
  end if;

  update public.credit_accounts
     set balance = balance - charge,
         lifetime_spent = lifetime_spent + charge,
         version = version + 1,
         updated_at = now()
   where id = account.id;

  insert into public.credit_reservations (user_id, account_id, metric, units, credits, idempotency_key, metadata)
  values (p_user_id, account.id, trim(p_metric), p_units, charge,
          coalesce(key_value, md5(random()::text || clock_timestamp()::text || p_user_id::text)),
          coalesce(p_metadata, '{}'::jsonb))
  returning * into reservation;

  insert into public.credit_ledger (user_id, account_id, reservation_id, entry_type, delta, balance_after, metric, idempotency_key, reason, metadata)
  values (p_user_id, account.id, reservation.id, 'reserve', -charge, account.balance - charge, trim(p_metric),
          'reservation:' || reservation.id::text, '预扣积分', coalesce(p_metadata, '{}'::jsonb));

  return query select true, 'RESERVED', reservation.id, charge, account.balance - charge;
exception when unique_violation then
  select * into reservation from public.credit_reservations where user_id = p_user_id and idempotency_key = key_value;
  if reservation.id is not null and reservation.status in ('reserved', 'committed') then
    return query select true, 'IDEMPOTENT_REPLAY', reservation.id, reservation.credits, 0::numeric;
  end if;
  raise;
end;
$$;

create or replace function public.settle_credits(
  p_reservation_id bigint,
  p_status text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  reservation public.credit_reservations%rowtype;
  account public.credit_accounts%rowtype;
begin
  if p_status not in ('committed', 'released') then return false; end if;
  select * into reservation from public.credit_reservations where id = p_reservation_id for update;
  if reservation.id is null or reservation.status <> 'reserved' then return false; end if;
  if p_status = 'committed' then
    update public.credit_reservations set status = 'committed', settled_at = now() where id = reservation.id;
    return true;
  end if;

  select * into account from public.credit_accounts where id = reservation.account_id for update;
  update public.credit_accounts
     set balance = balance + reservation.credits,
         lifetime_spent = greatest(0, lifetime_spent - reservation.credits),
         version = version + 1,
         updated_at = now()
   where id = account.id;
  insert into public.credit_ledger (user_id, account_id, reservation_id, entry_type, delta, balance_after, metric, idempotency_key, reason, metadata)
  values (reservation.user_id, account.id, reservation.id, 'refund', reservation.credits, account.balance + reservation.credits,
          reservation.metric, 'refund:' || reservation.id::text, 'AI 调用失败退回积分', reservation.metadata);
  update public.credit_reservations set status = 'released', settled_at = now() where id = reservation.id;
  return true;
end;
$$;

create or replace function public.grant_credits(
  p_user_id uuid,
  p_amount numeric,
  p_entry_type text default 'grant',
  p_idempotency_key text default null,
  p_reason text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns table (account_id bigint, balance numeric, ledger_id bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  account public.credit_accounts%rowtype;
  v_ledger_id bigint;
  key_value text := nullif(trim(coalesce(p_idempotency_key, '')), '');
begin
  if p_user_id is null or p_amount = 0 or p_entry_type not in ('grant', 'purchase', 'adjustment') then
    raise exception 'invalid credit grant';
  end if;
  if key_value is not null and exists (select 1 from public.credit_ledger where user_id = p_user_id and idempotency_key = key_value) then
    select a.* into account from public.credit_accounts a where a.user_id = p_user_id;
    select l.id into v_ledger_id from public.credit_ledger l where l.user_id = p_user_id and l.idempotency_key = key_value;
    return query select account.id, account.balance, v_ledger_id;
    return;
  end if;
  insert into public.credit_accounts (user_id) values (p_user_id) on conflict (user_id) do nothing;
  select * into account from public.credit_accounts where user_id = p_user_id for update;
  if account.balance + p_amount < 0 then raise exception 'credit balance cannot be negative'; end if;
  update public.credit_accounts as credit_account
     set balance = credit_account.balance + p_amount,
         lifetime_granted = credit_account.lifetime_granted + case when p_amount > 0 then p_amount else 0 end,
         version = credit_account.version + 1,
         updated_at = now()
   where id = account.id
   returning * into account;
  insert into public.credit_ledger (user_id, account_id, entry_type, delta, balance_after, idempotency_key, reason, metadata)
  values (p_user_id, account.id, p_entry_type, p_amount, account.balance, key_value, p_reason, coalesce(p_metadata, '{}'::jsonb))
  returning id into v_ledger_id;
  return query select account.id, account.balance, v_ledger_id;
end;
$$;

revoke all on function public.reserve_credits(uuid, text, numeric, text, boolean, jsonb) from public;
revoke all on function public.settle_credits(bigint, text) from public;
revoke all on function public.grant_credits(uuid, numeric, text, text, text, jsonb) from public;
grant execute on function public.reserve_credits(uuid, text, numeric, text, boolean, jsonb) to service_role;
grant execute on function public.settle_credits(bigint, text) to service_role;
grant execute on function public.grant_credits(uuid, numeric, text, text, text, jsonb) to service_role;

commit;
