begin;

create table if not exists public.billing_plans (
  id bigint generated by default as identity primary key,
  plan_code text not null unique,
  plan_type text not null default 'one_time',
  name jsonb not null default '{}'::jsonb,
  description jsonb not null default '{}'::jsonb,
  currency text not null default 'CNY',
  amount_minor bigint not null default 0,
  credits numeric(18, 4) not null default 0,
  duration_days integer,
  is_active boolean not null default true,
  display_order integer not null default 0,
  version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint billing_plans_type_check check (plan_type in ('one_time', 'subscription', 'free')),
  constraint billing_plans_currency_check check (currency ~ '^[A-Z]{3}$'),
  constraint billing_plans_amount_check check (amount_minor >= 0),
  constraint billing_plans_credits_check check (credits >= 0),
  constraint billing_plans_duration_check check (duration_days is null or duration_days > 0)
);

alter table public.billing_orders
  add column if not exists order_no text,
  add column if not exists plan_id bigint references public.billing_plans(id),
  add column if not exists amount_minor bigint,
  add column if not exists credits_granted numeric(18, 4) not null default 0,
  add column if not exists price_version integer not null default 1,
  add column if not exists checkout_context jsonb not null default '{}'::jsonb,
  add column if not exists paid_at timestamptz,
  add column if not exists refunded_at timestamptz;

alter table public.billing_orders drop constraint if exists billing_orders_status_check;
alter table public.billing_orders add constraint billing_orders_status_check check (
  status in ('pending', 'paid', 'cancelled', 'refunded', 'partially_refunded', 'failed', 'expired')
);

create unique index if not exists billing_orders_order_no_uidx
  on public.billing_orders(order_no)
  where order_no is not null;

create table if not exists public.payment_attempts (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.billing_orders(id) on delete cascade,
  provider text not null,
  channel text not null,
  merchant_order_no text not null unique,
  provider_trade_no text,
  status text not null default 'created',
  amount_minor bigint not null,
  currency text not null default 'CNY',
  qr_code text,
  redirect_url text,
  provider_payload jsonb not null default '{}'::jsonb,
  failure_reason text,
  paid_at timestamptz,
  refunded_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payment_attempts_channel_check check (
    channel in ('wechat_native', 'wechat_h5', 'wechat_jsapi', 'alipay_qr', 'alipay_wap', 'manual')
  ),
  constraint payment_attempts_status_check check (
    status in ('created', 'pending', 'paid', 'failed', 'cancelled', 'refunded', 'partially_refunded', 'expired')
  ),
  constraint payment_attempts_amount_check check (amount_minor >= 0),
  constraint payment_attempts_currency_check check (currency ~ '^[A-Z]{3}$')
);

create index if not exists payment_attempts_order_created_idx
  on public.payment_attempts(order_id, created_at desc);
create unique index if not exists payment_attempts_provider_trade_uidx
  on public.payment_attempts(provider, provider_trade_no)
  where provider_trade_no is not null;

alter table public.billing_plans enable row level security;
alter table public.payment_attempts enable row level security;

drop policy if exists billing_plans_public_select on public.billing_plans;
create policy billing_plans_public_select on public.billing_plans
  for select to anon, authenticated using (is_active = true);

drop policy if exists payment_attempts_owner_select on public.payment_attempts;
create policy payment_attempts_owner_select on public.payment_attempts
  for select to authenticated using (
    exists (
      select 1 from public.billing_orders orders
      where orders.id = payment_attempts.order_id
        and orders.user_id = auth.uid()
    )
  );

revoke all on public.billing_plans, public.payment_attempts from anon, authenticated;
grant select on public.billing_plans to anon, authenticated;
grant select on public.payment_attempts to authenticated;
grant select, insert, update, delete on public.billing_plans, public.payment_attempts to service_role;
grant usage, select on sequence public.billing_plans_id_seq, public.payment_attempts_id_seq to service_role;

insert into public.billing_plans
  (plan_code, plan_type, name, description, currency, amount_minor, credits, duration_days, display_order, metadata)
values
  ('free', 'free', '{"zh-CN":"免费体验","zh-TW":"免費體驗","en":"Free trial"}'::jsonb, '{"zh-CN":"体验基础求职功能","zh-TW":"體驗基礎求職功能","en":"Try the core job-search features"}'::jsonb, 'CNY', 0, 120, null, 10, '{"one_time":true}'::jsonb),
  ('cn_explorer_49', 'one_time', '{"zh-CN":"体验包","zh-TW":"體驗包","en":"Explorer"}'::jsonb, '{"zh-CN":"适合偶尔使用 AI 的求职者","zh-TW":"適合偶爾使用 AI 的求職者","en":"For occasional AI-assisted job searches"}'::jsonb, 'CNY', 4900, 500, 365, 20, '{}'::jsonb),
  ('cn_job_99', 'one_time', '{"zh-CN":"求职包","zh-TW":"求職包","en":"Job search"}'::jsonb, '{"zh-CN":"适合集中求职阶段","zh-TW":"適合集中求職階段","en":"For an active job-search cycle"}'::jsonb, 'CNY', 9900, 1200, 365, 30, '{"recommended":true}'::jsonb),
  ('cn_high_199', 'one_time', '{"zh-CN":"高频包","zh-TW":"高頻包","en":"High volume"}'::jsonb, '{"zh-CN":"适合高频使用 AI 的求职者","zh-TW":"適合高頻使用 AI 的求職者","en":"For frequent AI usage"}'::jsonb, 'CNY', 19900, 2800, 365, 40, '{}'::jsonb),
  ('cn_pro_monthly', 'subscription', '{"zh-CN":"Pro 月卡","zh-TW":"Pro 月卡","en":"Pro monthly"}'::jsonb, '{"zh-CN":"持续求职与简历优化","zh-TW":"持續求職與履歷優化","en":"Ongoing job search and resume optimization"}'::jsonb, 'CNY', 12900, 1800, 30, 50, '{}'::jsonb),
  ('cn_career_monthly', 'subscription', '{"zh-CN":"Career 月卡","zh-TW":"Career 月卡","en":"Career monthly"}'::jsonb, '{"zh-CN":"面试、选岗和优化高频使用","zh-TW":"面試、選崗和優化高頻使用","en":"High-frequency matching, interviews, and optimization"}'::jsonb, 'CNY', 24900, 4500, 30, 60, '{}'::jsonb)
on conflict (plan_code) do nothing;

commit;
